system_clocks = { clock_tree = [
    # High-speed clock sources
    { name = "XTAL_CLK",    type = "source", values = "40",      output = "VALUE * 1_000_000", always_on = true },
    { name = "RC_FAST_CLK", type = "source",                     output = "17_500_000" },
    { name = "PLL_CLK",     type = "derived", from = "XTAL_CLK", output = "480_000_000" },

    # Low-speed clocks
    { name = "XTAL32K_CLK",  type = "source", output = "32768"   },
    { name = "OSC_SLOW_CLK", type = "source", output = "32768"   },
    { name = "RC_SLOW_CLK",  type = "source", output = "136_000" },

    # PLL divider taps
    { name = "PLL_F20M",  type = "generic", output = "PLL_CLK / 24" },
    { name = "PLL_F40M",  type = "generic", output = "PLL_CLK / 12" },
    { name = "PLL_F48M",  type = "generic", output = "PLL_CLK / 10" },
    { name = "PLL_F60M",  type = "generic", output = "PLL_CLK / 8"  },
    { name = "PLL_F80M",  type = "generic", output = "PLL_CLK / 6"  },
    { name = "PLL_F120M", type = "generic", output = "PLL_CLK / 4"  },
    { name = "PLL_F160M", type = "generic", output = "PLL_CLK / 3"  },

    # HP SOC clock root (PCR_SOC_CLK_SEL: XTAL, RC_FAST, PLL_F160M)
    { name = "HP_ROOT_CLK", type = "mux", variants = [
        { name = "XTAL",      outputs = "XTAL_CLK" },
        { name = "RC_FAST",   outputs = "RC_FAST_CLK" },
        { name = "PLL_F160M", outputs = "PLL_F160M" },
    ] },

    { name = "CPU_CLK", type = "generic", params = { divisor = "0..256" }, output = "HP_ROOT_CLK / (divisor + 1)" },

    # AHB_CLK divider: divider = (AHB_DIV_NUM + 1), <= 40MHz
    { name = "AHB_CLK", type = "generic", params = { divisor = "0..256" }, output = "HP_ROOT_CLK / (divisor + 1)" },

    { name = "APB_CLK", type = "generic", params = { divisor = "0..256" }, output = "AHB_CLK / (divisor + 1)" },

    { name = "XTAL_D2_CLK", type = "generic", output = "XTAL_CLK / 2" },
    { name = "LP_FAST_CLK", type = "mux", variants = [
        { name = "RC_FAST", outputs = "RC_FAST_CLK" },
        { name = "XTAL_D2", outputs = "XTAL_D2_CLK" },
        { name = "XTAL",    outputs = "XTAL_CLK" },
    ] },
    { name = "LP_SLOW_CLK", type = "mux", variants = [
        { name = "RC_SLOW",  outputs = "RC_SLOW_CLK" },
        { name = "XTAL32K",  outputs = "XTAL32K_CLK" },
        { name = "OSC_SLOW", outputs = "OSC_SLOW_CLK" },
    ] },

    { name = "TIMG_CALIBRATION_CLOCK", type = "mux", variants = [
        { name = "OSC_SLOW_CLK",    outputs = "OSC_SLOW_CLK" },
        { name = "RC_SLOW_CLK",     outputs = "RC_SLOW_CLK" },
        { name = "RC_FAST_DIV_CLK", outputs = "RC_FAST_CLK" },
        { name = "XTAL32K_CLK",     outputs = "XTAL32K_CLK" },
    ] },
], template_groups = [
    { group = "UART", clocks = [
        { name = "FUNCTION_CLOCK", type = "generic", output = "sclk / (div_num + 1)", params = { sclk = [
            { name = "XTAL",     outputs = "XTAL_CLK", default = true },
            { name = "PLL_F80M", outputs = "PLL_F80M" }, # in IDF, PLL_F80M is used, but in fact we'll just increase power consumption with it.
            { name = "RC_FAST",  outputs = "RC_FAST_CLK" },
        ], div_num = "0 .. 0x100" } },
        { name = "BAUD_RATE_GENERATOR", type = "generic", output = "(FUNCTION_CLOCK * 16) / (integral * 16 + fractional)", params = { fractional = "0..16", integral = "0..0x1000" } },
    ] },
    { group = "TIMG", clocks = [
        { name = "FUNCTION_CLOCK", type = "mux", variants = [
            { name = "XTAL_CLK",    outputs = "XTAL_CLK", default = true },
            { name = "RC_FAST_CLK", outputs = "RC_FAST_CLK" },
            { name = "PLL_F80M",    outputs = "PLL_F80M" },
        ] },
        { name = "WDT_CLOCK", type = "mux", variants = [
            { name = "XTAL_CLK",    outputs = "XTAL_CLK", default = true },
            { name = "RC_FAST_CLK", outputs = "RC_FAST_CLK" },
            { name = "PLL_F80M",    outputs = "PLL_F80M" },
        ] },
    ] },
    { group = "I2C", clocks = [
        { name = "FUNCTION_CLOCK", type = "generic", output = "sclk / (div_num + 1)", params = { sclk = [
            { name = "XTAL",    outputs = "XTAL_CLK", default = true },
            { name = "RC_FAST", outputs = "RC_FAST_CLK" },
        ], div_num = "0 .. 0x100" } },
    ] },
    { group = "SPI", clocks = [
        { name = "FUNCTION_CLOCK", type = "mux", variants = [
            { name = "XTAL",      outputs = "XTAL_CLK", default = true },
            { name = "PLL_F160M", outputs = "PLL_F160M" },
            { name = "RC_FAST",   outputs = "RC_FAST_CLK" },
        ] },
    ] },
] }

peripheral_clocks = { templates = [
    { name = "default_clk_en_template", value = "{{control}}::regs().{{conf_register}}().modify(|_, w| w.{{clk_en_field}}().bit(enable));" },
    { name = "clk_en_template", value = "{{default_clk_en_template}}" },
    { name = "rst_template", value = "{{control}}::regs().{{conf_register}}().modify(|_, w| w.{{rst_field}}().bit(reset));" },
    { name = "control", value = "crate::peripherals::SYSTEM" },
    { name = "conf_register", value = "{{peripheral}}_conf" },
    { name = "clk_en_field", value = "{{peripheral}}_clk_en" },
    { name = "rst_field", value = "{{peripheral}}_rst_en" },
], peripheral_clocks = [
    { name = "Uart0", template_params = { conf_register = "uart(0).conf", clk_en_field = "clk_en", rst_field = "rst_en" }, keep_enabled = true },
    { name = "Uart1", template_params = { conf_register = "uart(1).conf", clk_en_field = "clk_en", rst_field = "rst_en" } },
    { name = "Timg0", template_params = { conf_register = "timergroup(0).conf", clk_en_field = "clk_en", rst_field = "rst_en" }, keep_enabled = true },
    { name = "Timg1", template_params = { conf_register = "timergroup(1).conf", clk_en_field = "clk_en", rst_field = "rst_en" } },
    { name = "I2cExt0", template_params = { peripheral = "i2c0" }},
    { name = "AhbGdma", template_params = { peripheral = "gdma" } },
    { name = "I2s0", template_params = { peripheral = "i2s" } },
    { name = "Spi2" },

    { name = "Sha" },
    { name = "Ecc" },
    { name = "Systimer", template_params = { peripheral = "systimer" }, keep_enabled = true },
    { name = "UsbDevice", keep_enabled = true },
] }
