version = 2
has_input_sync = true
gpio_function = 1
constant_0_input = 0x60
constant_1_input = 0x40
pins = [
    { pin =  0,                                                                            analog = { 0 = "XTAL_32K_P"                 }, lp = { 1 = "LP_GPIO0" }},
    { pin =  1,                                                                            analog = { 0 = "XTAL_32K_N", 1 = "ADC1_CH0" }, lp = { 1 = "LP_GPIO1" }},
    { pin =  2,  functions = {               2 = "FSPIQ"  },                               analog = {                   1 = "ADC1_CH1" }, lp = { 1 = "LP_GPIO2" }},
    { pin =  3,  functions = { 0 = "MTMS",   2 = "FSPIHD" },  limitations = ["strapping"], analog = {                   1 = "ADC1_CH2" }, lp = { 1 = "LP_GPIO3" }},
    { pin =  4,  functions = { 0 = "MTDI",   2 = "FSPIWP" },  limitations = ["strapping"], analog = {                   1 = "ADC1_CH3" }, lp = { 1 = "LP_GPIO4" }},
    { pin =  5,  functions = { 0 = "MTCK" },                                                                                              lp = { 1 = "LP_GPIO5" }},
    { pin =  6,  functions = { 0 = "MTDO",   2 = "FSPICLK" },                                                                             lp = { 1 = "LP_GPIO6" }},
    { pin =  7,  functions = {               2 = "FSPID"   }, limitations = ["strapping"] },
    { pin =  8,  functions = {               2 = "FSPICS0" }, limitations = ["strapping"], analog = { 0 = "ZCD0" } },
    { pin =  9,                                               limitations = ["strapping"], analog = { 0 = "ZCD1" } },
    { pin =  10, functions = { 0 = "U0RXD" } },
    { pin =  11, functions = { 0 = "U0TXD" } },
    { pin =  12,                                                                           analog = { 0 = "USJ_DM" } },
    { pin =  13,                                                                           analog = { 0 = "USJ_DP" } },
    { pin =  14, functions = { 0 = "FSPICS1" },               limitations = ["spi_psram"] },
    { pin =  15, functions = { 0 = "FSPICS0" },               limitations = ["spi_flash"] },
    { pin =  16, functions = { 0 = "FSPIQ" },                 limitations = ["spi_flash", "spi_psram"] },
    { pin =  17, functions = { 0 = "FSPIWP" },                limitations = ["spi_flash", "spi_psram"] },
    { pin =  18,                                              limitations = ["spi_flash", "spi_psram"] },
    { pin =  19, functions = { 0 = "FSPIHD" },                limitations = ["spi_flash", "spi_psram"] },
    { pin =  20, functions = { 0 = "FSPICLK" },               limitations = ["spi_flash", "spi_psram"] },
    { pin =  21, functions = { 0 = "FSPID" },                 limitations = ["spi_flash", "spi_psram"] },
    { pin =  22, functions = { 0 = "SDIO_DATA2" } },
    { pin =  23, functions = { 0 = "SDIO_DATA3" } },
    { pin =  24 },
    { pin =  25, functions = { 0 = "SDIO_CMD" } },
    { pin =  26, functions = { 0 = "SDIO_CLK" } },
    { pin =  27, functions = { 0 = "SDIO_DATA0" } },
    { pin =  28, functions = { 0 = "SDIO_DATA1" } },
    { pin =  29 },
]
input_signals = [
    { name = "U0RXD",               id = 6 },
    { name = "U0CTS",               id = 7 },
    { name = "U0DSR",               id = 8 },
    { name = "U1RXD",               id = 9 },
    { name = "U1CTS",               id = 10 },
    { name = "U1DSR",               id = 11 },
    { name = "I2S_MCLK",            id = 12 },
    { name = "I2SO_BCK",            id = 13 },
    { name = "I2SO_WS",             id = 14 },
    { name = "I2SI_SD",             id = 15 },
    { name = "I2SI_BCK",            id = 16 },
    { name = "I2SI_WS",             id = 17 },
    { name = "CPU_GPIO_0",          id = 27 },
    { name = "CPU_GPIO_1",          id = 28 },
    { name = "CPU_GPIO_2",          id = 29 },
    { name = "CPU_GPIO_3",          id = 30 },
    { name = "CPU_GPIO_4",          id = 31 },
    { name = "CPU_GPIO_5",          id = 32 },
    { name = "CPU_GPIO_6",          id = 33 },
    { name = "CPU_GPIO_7",          id = 34 },
    { name = "USB_JTAG_TDO_BRIDGE", id = 35 },
    { name = "I2CEXT0_SCL",         id = 46 },
    { name = "I2CEXT0_SDA",         id = 47 },
    { name = "FSPICLK",             id = 64 },
    { name = "FSPIQ",               id = 65 },
    { name = "FSPID",               id = 66 },
    { name = "FSPIHD",              id = 67 },
    { name = "FSPIWP",              id = 68 },
    { name = "FSPICS0",             id = 69 },
    { name = "U2RXD",               id = 72 },
    { name = "U2CTS",               id = 73 },
    { name = "U2DSR",               id = 74 },
    { name = "SIG_IN_FUNC97",       id = 97 },
    { name = "SIG_IN_FUNC98",       id = 98 },
    { name = "SIG_IN_FUNC99",       id = 99 },
    { name = "SIG_IN_FUNC100",      id = 100 },

    { name = "SDIO_CLK" },
    { name = "SDIO_CMD" },
    { name = "SDIO_DATA0" },
    { name = "SDIO_DATA1" },
    { name = "SDIO_DATA2" },
    { name = "SDIO_DATA3" },

    { name = "MTDI" },
    { name = "MTDO" },
    { name = "MTCK" },
    { name = "MTMS" },
]
output_signals = [
    { name = "LEDC_LS_SIG0",          id = 0 },
    { name = "LEDC_LS_SIG1",          id = 1 },
    { name = "LEDC_LS_SIG2",          id = 2 },
    { name = "LEDC_LS_SIG3",          id = 3 },
    { name = "LEDC_LS_SIG4",          id = 4 },
    { name = "LEDC_LS_SIG5",          id = 5 },
    { name = "U0TXD",                 id = 6 },
    { name = "U0RTS",                 id = 7 },
    { name = "U0DTR",                 id = 8 },
    { name = "U1TXD",                 id = 9 },
    { name = "U1RTS",                 id = 10 },
    { name = "U1DTR",                 id = 11 },
    { name = "I2S_MCLK",              id = 12 },
    { name = "I2SO_BCK",              id = 13 },
    { name = "I2SO_WS",               id = 14 },
    { name = "I2SO_SD",               id = 15 },
    { name = "I2SI_BCK",              id = 16 },
    { name = "I2SI_WS",               id = 17 },
    { name = "I2SO_SD1",              id = 18 },
    { name = "CPU_GPIO_0",            id = 27 },
    { name = "CPU_GPIO_1",            id = 28 },
    { name = "CPU_GPIO_2",            id = 29 },
    { name = "CPU_GPIO_3",            id = 30 },
    { name = "CPU_GPIO_4",            id = 31 },
    { name = "CPU_GPIO_5",            id = 32 },
    { name = "CPU_GPIO_6",            id = 33 },
    { name = "CPU_GPIO_7",            id = 34 },
    { name = "I2CEXT0_SCL",           id = 46 },
    { name = "I2CEXT0_SDA",           id = 47 },
    { name = "FSPICLK",               id = 64 },
    { name = "FSPIQ",                 id = 65 },
    { name = "FSPID",                 id = 66 },
    { name = "FSPIHD",                id = 67 },
    { name = "FSPIWP",                id = 68 },
    { name = "FSPICS0",               id = 69 },
    { name = "U2TXD",                 id = 72 },
    { name = "U2RTS",                 id = 73 },
    { name = "U2DTR",                 id = 74 },
    { name = "FSPICS1",               id = 102 },
    { name = "FSPICS2",               id = 103 },
    { name = "FSPICS3",               id = 104 },
    { name = "FSPICS4",               id = 105 },
    { name = "FSPICS5",               id = 106 },
    { name = "SDIO_TOHOST_INT",       id = 124 },
    { name = "GPIO",                  id = 256 },
]
