#!/usr/bin/env bash

# Exit immediately on first non-zero status from a command in the script.
set -o errexit

# Ensure all tools being used are available.
command -v "cargo" >/dev/null 2>&1 || { echo >&2 "The 'cargo' command is not installed, exiting"; exit 1; }
command -v "rustfmt" >/dev/null 2>&1 || { echo >&2 "The 'rustfmt' command is not installed, exiting"; exit 1; }

# Check the formatting of all Rust code for every package.
for package in "esp"*/; do
    # Check package is correctly formatted.
    cargo fmt --all --manifest-path "${package}Cargo.toml" -- --check
done
