version = 2
has_input_sync = true
gpio_function = 1
constant_0_input = 0x1f
constant_1_input = 0x1e
pins = [
    { pin =  0,                                                           analog = { 1 = "ADC1_CH0" }, rtc = { 0 = "RTC_GPIO0" } },
    { pin =  1,                                                           analog = { 1 = "ADC1_CH1" }, rtc = { 0 = "RTC_GPIO1" } },
    { pin =  2, functions = { 2 = "FSPIQ" }, limitations = ["strapping"], analog = { 1 = "ADC1_CH2" }, rtc = { 0 = "RTC_GPIO2" } },
    { pin =  3,                                                           analog = { 1 = "ADC1_CH3" }, rtc = { 0 = "RTC_GPIO3" } },
    { pin =  4, functions = { 0 = "MTMS", 2 = "FSPIHD"  },                analog = { 1 = "ADC1_CH4" }, rtc = { 0 = "RTC_GPIO4" } },
    { pin =  5, functions = { 0 = "MTDI", 2 = "FSPIWP"  },                analog = { 1 = "ADC2_CH0" }, rtc = { 0 = "RTC_GPIO5" } },
    { pin =  6, functions = { 0 = "MTCK", 2 = "FSPICLK" } },
    { pin =  7, functions = { 0 = "MTDO", 2 = "FSPID"   } },
    { pin =  8,                                            limitations = ["strapping"] },
    { pin =  9,                                            limitations = ["strapping"] },
    { pin = 10, functions = { 2 = "FSPICS0" } },
    { pin = 11,                               limitations = ["spi_flash"] },
    { pin = 12, functions = { 0 = "SPIHD" },  limitations = ["spi_flash"] },
    { pin = 13, functions = { 0 = "SPIWP" },  limitations = ["spi_flash"] },
    { pin = 14, functions = { 0 = "SPICS0" }, limitations = ["spi_flash"] },
    { pin = 15, functions = { 0 = "SPICLK" }, limitations = ["spi_flash"] },
    { pin = 16, functions = { 0 = "SPID" },   limitations = ["spi_flash"] },
    { pin = 17, functions = { 0 = "SPIQ" },   limitations = ["spi_flash"] },
    { pin = 18,                          analog = { 0 = "USJ_DM" } },
    { pin = 19,                          analog = { 0 = "USJ_DP" } },
    { pin = 20, functions = { 0 = "U0RXD" } },
    { pin = 21, functions = { 0 = "U0TXD" } },
]
input_signals = [
    { name = "SPIQ",             id = 0 },
    { name = "SPID",             id = 1 },
    { name = "SPIHD",            id = 2 },
    { name = "SPIWP",            id = 3 },
    { name = "U0RXD",            id = 6 },
    { name = "U0CTS",            id = 7 },
    { name = "U0DSR",            id = 8 },
    { name = "U1RXD",            id = 9 },
    { name = "U1CTS",            id = 10 },
    { name = "U1DSR",            id = 11 },
    { name = "I2S_MCLK",         id = 12 },
    { name = "I2SO_BCK",         id = 13 },
    { name = "I2SO_WS",          id = 14 },
    { name = "I2SI_SD",          id = 15 },
    { name = "I2SI_BCK",         id = 16 },
    { name = "I2SI_WS",          id = 17 },
    { name = "GPIO_BT_PRIORITY", id = 18 },
    { name = "GPIO_BT_ACTIVE",   id = 19 },
    { name = "CPU_GPIO_0",       id = 28 },
    { name = "CPU_GPIO_1",       id = 29 },
    { name = "CPU_GPIO_2",       id = 30 },
    { name = "CPU_GPIO_3",       id = 31 },
    { name = "CPU_GPIO_4",       id = 32 },
    { name = "CPU_GPIO_5",       id = 33 },
    { name = "CPU_GPIO_6",       id = 34 },
    { name = "CPU_GPIO_7",       id = 35 },
    { name = "EXT_ADC_START",    id = 45 },
    { name = "RMT_SIG_0",        id = 51 },
    { name = "RMT_SIG_1",        id = 52 },
    { name = "I2CEXT0_SCL",      id = 53 },
    { name = "I2CEXT0_SDA",      id = 54 },
    { name = "FSPICLK",          id = 63 },
    { name = "FSPIQ",            id = 64 },
    { name = "FSPID",            id = 65 },
    { name = "FSPIHD",           id = 66 },
    { name = "FSPIWP",           id = 67 },
    { name = "FSPICS0",          id = 68 },
    { name = "TWAI_RX",          id = 74 },
    { name = "SIG_FUNC_97",      id = 97 },
    { name = "SIG_FUNC_98",      id = 98 },
    { name = "SIG_FUNC_99",      id = 99 },
    { name = "SIG_FUNC_100",     id = 100 },

    { name = "MTCK" },
    { name = "MTMS" },
    { name = "MTDI" },
]
output_signals = [
    { name = "SPIQ",             id = 0 },
    { name = "SPID",             id = 1 },
    { name = "SPIHD",            id = 2 },
    { name = "SPIWP",            id = 3 },
    { name = "SPICLK",           id = 4 },
    { name = "SPICS0",           id = 5 },
    { name = "U0TXD",            id = 6 },
    { name = "U0RTS",            id = 7 },
    { name = "U0DTR",            id = 8 },
    { name = "U1TXD",            id = 9 },
    { name = "U1RTS",            id = 10 },
    { name = "U1DTR",            id = 11 },
    { name = "I2S_MCLK",         id = 12 },
    { name = "I2SO_BCK",         id = 13 },
    { name = "I2SO_WS",          id = 14 },
    { name = "I2SO_SD",          id = 15 },
    { name = "I2SI_BCK",         id = 16 },
    { name = "I2SI_WS",          id = 17 },
    { name = "GPIO_WLAN_PRIO",   id = 18 },
    { name = "GPIO_WLAN_ACTIVE", id = 19 },
    { name = "CPU_GPIO_0",       id = 28 },
    { name = "CPU_GPIO_1",       id = 29 },
    { name = "CPU_GPIO_2",       id = 30 },
    { name = "CPU_GPIO_3",       id = 31 },
    { name = "CPU_GPIO_4",       id = 32 },
    { name = "CPU_GPIO_5",       id = 33 },
    { name = "CPU_GPIO_6",       id = 34 },
    { name = "CPU_GPIO_7",       id = 35 },
    { name = "USB_JTAG_TCK",     id = 36 },
    { name = "USB_JTAG_TMS",     id = 37 },
    { name = "USB_JTAG_TDI",     id = 38 },
    { name = "USB_JTAG_TDO",     id = 39 },
    { name = "LEDC_LS_SIG0",     id = 45 },
    { name = "LEDC_LS_SIG1",     id = 46 },
    { name = "LEDC_LS_SIG2",     id = 47 },
    { name = "LEDC_LS_SIG3",     id = 48 },
    { name = "LEDC_LS_SIG4",     id = 49 },
    { name = "LEDC_LS_SIG5",     id = 50 },
    { name = "RMT_SIG_0",        id = 51 },
    { name = "RMT_SIG_1",        id = 52 },
    { name = "I2CEXT0_SCL",      id = 53 },
    { name = "I2CEXT0_SDA",      id = 54 },
    { name = "GPIO_SD0",         id = 55 },
    { name = "GPIO_SD1",         id = 56 },
    { name = "GPIO_SD2",         id = 57 },
    { name = "GPIO_SD3",         id = 58 },
    { name = "I2SO_SD1",         id = 59 },
    { name = "FSPICLK",          id = 63 },
    { name = "FSPIQ",            id = 64 },
    { name = "FSPID",            id = 65 },
    { name = "FSPIHD",           id = 66 },
    { name = "FSPIWP",           id = 67 },
    { name = "FSPICS0",          id = 68 },
    { name = "FSPICS1",          id = 69 },
    { name = "FSPICS3",          id = 70 },
    { name = "FSPICS2",          id = 71 },
    { name = "FSPICS4",          id = 72 },
    { name = "FSPICS5",          id = 73 },
    { name = "TWAI_TX",          id = 74 },
    { name = "TWAI_BUS_OFF_ON",  id = 75 },
    { name = "TWAI_CLKOUT",      id = 76 },
    { name = "ANT_SEL0",         id = 89 },
    { name = "ANT_SEL1",         id = 90 },
    { name = "ANT_SEL2",         id = 91 },
    { name = "ANT_SEL3",         id = 92 },
    { name = "ANT_SEL4",         id = 93 },
    { name = "ANT_SEL5",         id = 94 },
    { name = "ANT_SEL6",         id = 95 },
    { name = "ANT_SEL7",         id = 96 },
    { name = "SIG_FUNC_97",      id = 97 },
    { name = "SIG_FUNC_98",      id = 98 },
    { name = "SIG_FUNC_99",      id = 99 },
    { name = "SIG_FUNC_100",     id = 100 },
    { name = "CLK_OUT1",         id = 123 },
    { name = "CLK_OUT2",         id = 124 },
    { name = "CLK_OUT3",         id = 125 },
    { name = "SPICS1",           id = 126 },
    { name = "USB_JTAG_TRST",    id = 127 },
    { name = "GPIO",             id = 128 },

    { name = "MTDO" },
]
