use std::{collections::HashMap, io::Write, path::Path, process::Command};

use anyhow::{Context, Result, bail, ensure};
use cargo_semver_checks::ReleaseType;
use clap::Args;
use esp_metadata::Chip;
use serde::{Deserialize, Serialize};
use strum::IntoEnumIterator;
use toml_edit::{Item, Value};

use crate::{
    Package,
    Version,
    cargo::CargoToml,
    commands::{
        VersionBump,
        checker::min_package_update,
        do_version_bump,
        release::changelog_preview,
    },
    git::{BackportInfo, current_branch, parse_backport_branch},
};

/// Arguments for generating a release plan.
#[derive(Debug, Args)]
pub struct PlanArgs {
    /// Allow making a release from the current (non-main) branch. The
    /// branch is expected to exist in the upstream esp-hal repo.
    #[arg(long)]
    allow_non_main: bool,

    /// The packages to be released.
    #[arg(value_enum, default_values_t = Package::iter())]
    packages: Vec<Package>,
}

/// A package in the release plan.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PackagePlan {
    pub package: Package,
    pub semver_checked: bool,
    pub current_version: semver::Version,
    pub new_version: semver::Version,
    pub tag_name: String,
    /// The version bump that will be applied to the package.
    pub bump: VersionBump,
}

/// A release plan is a list of packages and their version increments.
///
/// The plan is generated by analyzing the workspace and its dependencies.
/// The order of the packages in the plan is important, as it determines the
/// order in which the packages are released.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Plan {
    /// The branch the release is made from.
    pub base: String,
    /// Short random slug that pins this plan to its release branch
    /// (`release-branch-<slug>`). Generated once when the plan is created and
    /// preserved across re-plans so re-runs of `execute-plan` target the same
    /// branch and PR.
    pub slug: String,
    /// Present when this plan was generated from a backport branch (e.g.
    /// `esp-hal-1.1.x`). Downstream steps use this to enforce patch-only bumps
    /// and skip inapplicable post-release work.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backport: Option<BackportInfo>,
    /// The packages to be released, in order.
    pub packages: Vec<PackagePlan>,
}

/// Generate a short base36 slug. Not cryptographically random — we only need
/// uniqueness across release attempts, and the slug is persisted in the plan
/// file so it survives re-runs.
fn generate_slug() -> String {
    let mut n = jiff::Timestamp::now().as_nanosecond() as u128;
    const CHARS: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyz";
    let mut slug = String::new();
    for _ in 0..6 {
        slug.push(CHARS[(n % 36) as usize] as char);
        n /= 36;
    }
    slug
}

/// Read the slug from an existing (finalized) plan file, so that re-running
/// `plan` preserves the release branch name. Returns `Ok(None)` when no plan
/// file exists yet. Bails with the same error as `Plan::from_path` if the
/// file is present but still carries its JSONC comment header — the user is
/// expected to finalize the plan before re-running.
fn read_existing_slug(plan_path: &Path) -> Result<Option<String>> {
    if !plan_path.exists() {
        return Ok(None);
    }
    let plan = Plan::from_path(plan_path)?;
    Ok(Some(plan.slug))
}

impl Plan {
    /// Load a release plan from a file.
    pub fn from_path(plan_path: &Path) -> Result<Self> {
        let plan_source = std::fs::read_to_string(&plan_path)
            .with_context(|| format!("Failed to read release plan from {}. Run `cargo xrelease plan` to generate a release plan.", plan_path.display()))?;

        if plan_source.lines().any(|line| line.starts_with("//")) {
            bail!(
                "The release plan has not been finalized. Please open the plan and follow the instructions in it."
            );
        }

        let plan = serde_json::from_str::<Plan>(&plan_source).with_context(|| {
            format!("Failed to parse release plan from {}", plan_path.display())
        })?;

        Ok(plan)
    }
}

/// Generate a release plan for the specified packages.
pub fn plan(workspace: &Path, args: PlanArgs) -> Result<()> {
    let (current_branch, backport) = ensure_main_branch(args.allow_non_main)?;

    // On a backport branch, scope to exactly the backport package. Each
    // backport branch serves a single package; dependencies have their own
    // branches and are released independently.
    let packages_to_release = if let Some(ref ctx) = backport {
        println!("Backport branch detected: releasing only {}.", ctx.package);
        vec![ctx.package]
    } else {
        // Recursively collect dependencies. A bit inefficient, but we don't
        // need to sort a lot.
        let mut pkgs = args
            .packages
            .iter()
            .filter(|p| p.is_published())
            .flat_map(|p| related_crates(workspace, *p))
            .collect::<Vec<_>>();

        pkgs.sort();
        pkgs.dedup();
        pkgs
    };

    let mut package_tomls = packages_to_release
        .iter()
        .map(|pkg| CargoToml::new(workspace, *pkg).map(|cargo_toml| (*pkg, cargo_toml)))
        .collect::<Result<HashMap<_, _>>>()?;

    // Determine package dependencies (package -> dependencies). Restrict deps
    // to the in-scope set so the graph is self-contained — otherwise
    // `topological_sort` spins forever waiting for a dep that will never be
    // emitted (e.g. on a backport branch where `packages_to_release` is just
    // the single backport package).
    let mut dep_graph = HashMap::new();
    for (package, toml) in package_tomls.iter_mut() {
        let deps = toml
            .repo_dependencies()
            .into_iter()
            .filter(|d| packages_to_release.contains(d))
            .collect();
        dep_graph.insert(*package, deps);
    }

    // Topological sort the packages into a release order. Note that this is not a stable order,
    // because the source data is a HashMap which does not have a stable insertion order. This is
    // okay, as long as the relationships of the dependencies are kept.
    let sorted = topological_sort(&dep_graph);
    log::debug!("Sorted packages: {:?}", sorted);

    for package in sorted.iter() {
        ensure!(
            package_tomls[&package].is_published(),
            "Cannot release {package}: package is not published. The command \
            would have released the following packages: {}",
            sorted
                .iter()
                .map(|p| p.to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
    }

    // Gather semver bump requirements
    let mut update_amounts = vec![];
    let all_chips = Chip::iter().collect::<Vec<_>>();

    let changed = collect_changed_packages(
        &sorted,
        // Read direct dependencies out of Cargo.toml
        &|p| CargoToml::new(workspace, p).unwrap().repo_dependencies(),
        &|p| package_changed_since_last_release(workspace, p),
    );

    for package in sorted.iter().copied() {
        let amount = if changed[&package] {
            let mut amount = if package.is_semver_checked() {
                min_package_update(workspace, package, &all_chips)?
            } else {
                let forever_unstable = if let Some(metadata) =
                    package_tomls[&package].espressif_metadata()
                    && let Some(Item::Value(forever_unstable)) = metadata.get("forever-unstable")
                {
                    // Special case: some packages are perma-unstable, meaning they won't ever have
                    // a stable release. For these packages, we always use a
                    // patch release.
                    if let Value::Boolean(forever_unstable) = forever_unstable {
                        *forever_unstable.value()
                    } else {
                        log::warn!(
                            "Invalid value for 'forever-unstable' in metadata - must be a boolean"
                        );
                        true
                    }
                } else {
                    false
                };

                if forever_unstable {
                    ReleaseType::Patch
                } else {
                    ReleaseType::Minor
                }
            };

            // On a backport branch, force all bumps to Patch.
            if backport.is_some() && amount != ReleaseType::Patch {
                log::info!(
                    "{}: overriding {:?} bump to Patch (backport branch)",
                    package,
                    amount
                );
                amount = ReleaseType::Patch;
            }

            log::debug!("{} needs {:?} version bump", package, amount);
            Some(amount)
        } else {
            log::debug!("{} has no changes since last release", package);
            None
        };

        update_amounts.push((package, amount));
    }

    // Generate plan file. The plan should include, as an ordered list, the packages
    // and their version increment.

    let plan_path = workspace.join("release_plan.jsonc");
    let plan_path = crate::windows_safe_path(&plan_path);

    // Preserve the slug from an existing plan file so that re-running `plan`
    // after tweaks keeps targeting the same release branch.
    let slug = read_existing_slug(&plan_path)?.unwrap_or_else(generate_slug);

    let plan = Plan {
        base: current_branch,
        slug,
        backport: backport.clone(),
        packages: update_amounts
            .into_iter()
            .filter_map(|(package, bump)| {
                bump.map(|b| {
                    let current_version = package_tomls[&package].package_version();

                    let bump = if !current_version.pre.is_empty() {
                        // Package is already in a pre-release cycle — continue it
                        // on the same base. Hand-edit the plan to start a new
                        // cycle on a bumped base (e.g. `1.1.0-alpha.0` from
                        // `1.0.0`) by also setting `base`.
                        VersionBump {
                            base: None,
                            pre: Some(
                                current_version
                                    .pre
                                    .as_str()
                                    .split('.')
                                    .next()
                                    .unwrap()
                                    .to_string(),
                            ),
                        }
                    } else {
                        let base = match b {
                            ReleaseType::Major => Version::Major,
                            ReleaseType::Minor => Version::Minor,
                            ReleaseType::Patch => Version::Patch,
                            _ => unreachable!(),
                        };
                        VersionBump {
                            base: Some(base),
                            pre: None,
                        }
                    };

                    let new_version = do_version_bump(&current_version, &bump).unwrap();
                    let tag_name = package.tag(&new_version);

                    PackagePlan {
                        package,
                        semver_checked: package.is_semver_checked(),
                        current_version,
                        new_version,
                        tag_name,
                        bump,
                    }
                })
            })
            .collect(),
    };

    log::debug!("Writing release plan to {}", plan_path.display());

    let mut plan_header = String::from(
        r#"// Release plan generated by xtask.
//
// This file is automatically generated and meant to be manually edited. Change the version bump
// where appropriate. Remove packages that should not be released. Delete the comment block to
// finalize the release plan, otherwise trying to apply the release plan will fail.
//
// This file contains each package that needs to be released. The order of the packages is
// important, the packages will be released in the order they appear in the release plan.
// This is done in case the tool gets the dependency graph wrong.
//
// This plan may also contain packages that do not need to be released. Please review them
// in case the release was triggered by commits that only included non-relevant changes. These
// packages can be removed from the plan.
//
// You don't need to change versions and tag names. The plan will be updated when applying the
// release plan. The release plan will then be added to the release PR and will be used to
// orchestrate the actual publishing process.
//
// For each package, this plan contains the version bump that will be applied.
// A bump has two orthogonal fields — `base` (how much to bump
// major.minor.patch) and `pre` (the pre-release identifier):
//
// - Stable bump:               `"bump": { "base": "Minor", "pre": null }`
// - Continue pre-release cycle:`"bump": { "base": null,    "pre": "beta" }`
// - Start a new pre-release cycle on a bumped base (e.g. 1.0.0 -> 1.1.0-alpha.0):
//                              `"bump": { "base": "Minor", "pre": "alpha" }`
//
// Starting a pre-release cycle from a stable version without also setting
// `base` is an error, as it would produce a version lower than the current
// one.
//
// CHANGELOG REVIEW REQUIRED
// Changelog entries from recently merged PRs have been collected and merged
// into each package's CHANGELOG.md (Unreleased section) and MIGRATING-*.md
// files. Please review and adjust those files before running execute-plan:
//   - Add, remove, or reword entries as appropriate.
//   - Ensure migration guide content is accurate and complete.
"#,
    );

    if backport.is_some() {
        plan_header.push_str(
            r#"//
// PATCH RELEASE from backport branch.
// All bumps have been forced to Patch. Do NOT change bumps to Minor or Major —
// only bug fixes should be included in patch releases.
"#,
        );
    }

    let mut plan_file = std::fs::File::create(&plan_path)
        .with_context(|| format!("Failed to create {plan_path:?}"))?;
    plan_file
        .write_all(plan_header.as_bytes())
        .with_context(|| format!("Failed to write to {plan_file:?}"))?;
    serde_json::to_writer_pretty(&mut plan_file, &plan)
        .with_context(|| format!("Failed to serialize {plan:?} as pretty-printed JSON"))?;
    log::debug!("Release plan written to {}", plan_path.display());

    println!("Release plan written to {}.", plan_path.display());
    println!("Please review the release plan and make changes where appropriate.");
    println!(
        "To apply the release plan, you'll need to remove the heading comment, save the \
        file, then run the following command: `cargo xrelease execute-plan`",
    );

    // Merge PR changelog entries directly into CHANGELOG.md / MIGRATING-*.md files.
    let modified = generate_changelog_draft(workspace, &plan);
    if modified.is_empty() {
        println!();
        println!(
            "Note: No changelog entries were merged. Run \
            `cargo xtask release changelog-preview` manually if needed."
        );
    } else {
        println!();
        println!("Merged changelog entries into the following files:");
        for path in &modified {
            println!("  {}", path.display());
        }
        println!(
            "Please review and adjust these files before running `cargo xrelease execute-plan`."
        );
    }

    Ok(())
}

fn collect_changed_packages(
    sorted: &[Package],
    direct_dependencies: &impl Fn(Package) -> Vec<Package>,
    is_changed: &impl Fn(Package) -> bool,
) -> HashMap<Package, bool> {
    let mut changed = HashMap::new();

    // Collect recursive dependencies.
    let mut all_dependencies_of = HashMap::new();
    for package in sorted.iter().copied() {
        let dependencies = related_crates_cb(package, direct_dependencies);
        all_dependencies_of.insert(package, dependencies);
    }

    // Check each package whether they should be considered for release. A package should be
    // released if it has changes since the last release, or if it depends on a package that has
    // changes.
    for package in sorted.iter().copied() {
        if changed.get(&package).copied() == Some(true) {
            // This package has already been marked as changed, so skip it.
            continue;
        }

        let is_changed = is_changed(package);
        changed.insert(package, is_changed);
        if is_changed {
            // Mark all direct and indirect _dependents_ as changed too.
            for (dependent, deps) in all_dependencies_of.iter() {
                if deps.contains(&package) {
                    changed.insert(*dependent, true);
                }
            }
        }
    }

    changed
}

/// Ensure we are on the main branch, or allow non-main if specified.
///
/// Backport branches (e.g. `esp-hal-1.1.x`) are always allowed without
/// `--allow-non-main`. Returns the branch name and, when applicable, the
/// parsed backport context.
pub fn ensure_main_branch(allow_non_main: bool) -> Result<(String, Option<BackportInfo>)> {
    let current_branch = current_branch()?;
    let backport = parse_backport_branch(&current_branch);

    if backport.is_some() {
        println!("Detected backport branch: {current_branch}");
    } else if allow_non_main {
        println!("Release will be made from branch: {current_branch}");
    } else {
        ensure!(
            current_branch == "main",
            "You are not on the main branch. Please switch to the main branch before running this command again, or add `--allow-non-main`."
        );
    }

    Ok((current_branch, backport))
}

fn package_changed_since_last_release(workspace: &Path, package: Package) -> bool {
    let toml = CargoToml::new(workspace, package).expect("Failed to load Cargo.toml");

    let last_version: semver::Version = toml.package_version();

    let last_tag = package.tag(&last_version);
    let mut commits = commits_since_tag(workspace, &toml.package_path(), &last_tag);

    if commits == 0 {
        // Try to look up the last tag in the git history and retry.
        let last_tag = Command::new("git")
            .args(["describe", "--tags", "--abbrev=0"])
            .current_dir(workspace)
            .output()
            .expect("Failed to get last tag");
        let last_tag = String::from_utf8_lossy(&last_tag.stdout);
        let last_tag = last_tag.trim();

        if !last_tag.is_empty() {
            commits = commits_since_tag(workspace, &toml.package_path(), last_tag);
        }
    }

    log::trace!("{package}: {commits} commits since last release");

    commits > 0
}

fn commits_since_tag(workspace: &Path, package_path: &Path, tag: &str) -> usize {
    let commits = Command::new("git")
        .args([
            "log",
            &format!("{tag}..HEAD"),
            "--oneline",
            &package_path.display().to_string(),
        ])
        .current_dir(workspace)
        .output()
        .expect("Failed to get commit count since last tag");

    let output = String::from_utf8_lossy(&commits.stdout);

    output.lines().filter(|l| !l.trim().is_empty()).count()
}

/// Collects dependencies recursively, based on a callback that provides direct dependencies.
///
/// This is an implementation detail of the `related_crates` function, separate for testing
/// purposes.
fn related_crates_cb(
    package: Package,
    direct_dependencies: &impl Fn(Package) -> Vec<Package>,
) -> Vec<Package> {
    let mut packages = vec![package];

    for dep in direct_dependencies(package) {
        for dep in related_crates_cb(dep, direct_dependencies) {
            if !packages.contains(&dep) {
                packages.push(dep);
            }
        }
    }

    packages
}

fn related_crates(workspace: &Path, package: Package) -> Vec<Package> {
    related_crates_cb(package, &|p| {
        CargoToml::new(workspace, p).unwrap().repo_dependencies()
    })
}

/// Merge PR changelog and migration guide entries from recently-merged PRs
/// directly into each package's `CHANGELOG.md` and `MIGRATING-*.md` files.
///
/// Returns the paths of files that were modified. Returns an empty list if the
/// `gh` CLI is unavailable, no entries were found, or any other non-fatal
/// problem occurred.
fn generate_changelog_draft(workspace: &Path, plan: &Plan) -> Vec<std::path::PathBuf> {
    if plan.packages.is_empty() {
        return vec![];
    }

    // Use the oldest last-release tag as the baseline so we don't miss entries
    // for packages that were last released earlier than others.
    let since_ref = plan
        .packages
        .iter()
        .map(|pkg| pkg.package.tag(&pkg.current_version))
        .min_by_key(|tag| tag_commit_timestamp(workspace, tag))
        .expect("packages is non-empty");

    // Map crate name → PackagePlan for quick lookup.
    let pkg_by_crate: HashMap<String, &PackagePlan> = plan
        .packages
        .iter()
        .map(|pkg| (pkg.package.to_string(), pkg))
        .collect();

    let (changelogs, migrations) = match changelog_preview::collect_changelogs(
        workspace, &since_ref, 500,
    ) {
        Ok(r) => r,
        Err(e) => {
            log::warn!(
                "Could not collect changelog entries (is `gh` installed and authenticated?): {e}"
            );
            return vec![];
        }
    };

    let mut modified: Vec<std::path::PathBuf> = Vec::new();

    // Merge changelog entries into each package's CHANGELOG.md.
    for (crate_name, new_entries) in &changelogs {
        let Some(_pkg) = pkg_by_crate.get(crate_name) else {
            continue;
        };
        if new_entries.format_unreleased().is_none() {
            continue;
        }

        let changelog_path = workspace.join(crate_name).join("CHANGELOG.md");
        let changelog_path = crate::windows_safe_path(&changelog_path);

        let written = match std::fs::write(&changelog_path, new_entries.to_string()) {
            Ok(()) => true,
            Err(e) => {
                log::warn!("Could not write {}: {e}", changelog_path.display());
                false
            }
        };
        if written {
            modified.push(changelog_path);
        }
    }

    // Append migration guide entries to each package's active MIGRATING-*.md.
    for (crate_name, entries) in &migrations {
        let Some(pkg) = pkg_by_crate.get(crate_name) else {
            continue;
        };

        // Patch releases don't have migration guides; skip them.
        if pkg.bump.base == Some(Version::Patch) {
            continue;
        }

        // The active migration guide is named after the current major.minor version
        // (zeroed patch). It was created by `post_release` after the previous release.
        let v = &pkg.current_version;
        let migration_file = format!("MIGRATING-{}.{}.0.md", v.major, v.minor);
        let migration_path = workspace.join(crate_name).join(&migration_file);
        let migration_path = crate::windows_safe_path(&migration_path);

        if !migration_path.exists() {
            log::warn!("Migration guide {migration_file} not found for {crate_name}; skipping.");
            continue;
        }

        let mut content = match std::fs::read_to_string(&migration_path) {
            Ok(c) => c,
            Err(e) => {
                log::warn!("Could not read {}: {e}", migration_path.display());
                continue;
            }
        };

        // Append each entry's guide text under its area heading.
        let mut appended = false;
        for (area, _pr, guide) in entries {
            if !content.ends_with('\n') {
                content.push('\n');
            }
            content.push('\n');
            if let Some(area) = area {
                content.push_str(&format!("## {area}\n\n"));
            }
            content.push_str(guide.trim_end());
            content.push('\n');
            appended = true;
        }

        if appended {
            match std::fs::write(&migration_path, &content) {
                Ok(()) => modified.push(migration_path),
                Err(e) => log::warn!("Could not write {}: {e}", migration_path.display()),
            }
        }
    }

    modified
}

/// Return the UNIX commit timestamp for `tag`, or `0` if unknown.
fn tag_commit_timestamp(workspace: &Path, tag: &str) -> i64 {
    Command::new("git")
        .args(["log", "-1", "--format=%ct", tag])
        .current_dir(workspace)
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .and_then(|s| s.trim().parse::<i64>().ok())
        .unwrap_or(0)
}

fn topological_sort(dep_graph: &HashMap<Package, Vec<Package>>) -> Vec<Package> {
    let mut sorted = Vec::new();
    let mut dep_graph = dep_graph.clone();
    while !dep_graph.is_empty() {
        let before = sorted.len();
        dep_graph.retain(|pkg, deps| {
            deps.retain(|dep| !sorted.contains(dep));

            if deps.is_empty() {
                sorted.push(*pkg);
                false
            } else {
                true
            }
        });

        // No package was removed this pass — the remaining graph is either
        // cyclic or references deps not in the graph. Either way, looping
        // again would spin forever. Panic with the offending state so a
        // future regression fails loudly instead of pegging a CPU.
        assert!(
            sorted.len() > before,
            "topological_sort made no progress; remaining graph: {dep_graph:?}"
        );
    }

    sorted
}

#[cfg(test)]
mod tests {
    use super::*;

    // Dependencies in this graph do not always reflect real dependencies, it is only a test of
    // correct function operation.
    fn sample_dep_graph() -> HashMap<Package, Vec<Package>> {
        //           |-------------+-> esp-hal -> esp-alloc
        // esp-rtos -+> esp-radio -|

        let mut dep_graph = HashMap::new();
        dep_graph.insert(Package::EspHal, vec![Package::EspAlloc]);
        dep_graph.insert(Package::EspRtos, vec![Package::EspHal, Package::EspRadio]);
        dep_graph.insert(Package::EspRadio, vec![Package::EspHal]);
        dep_graph.insert(Package::EspAlloc, vec![]);

        dep_graph
    }

    #[track_caller]
    fn assert_unstable_lists_equal(actual: &[Package], expected: &[Package]) {
        use std::collections::HashSet;
        let actual_set: HashSet<_> = actual.iter().collect();
        let expected_set: HashSet<_> = expected.iter().collect();
        assert_eq!(actual_set, expected_set);
    }

    #[test]
    fn test_topological_sort() {
        let dep_graph = sample_dep_graph();
        let sorted = topological_sort(&dep_graph);

        assert_eq!(
            sorted,
            [
                Package::EspAlloc,
                Package::EspHal,
                Package::EspRadio,
                Package::EspRtos
            ]
        );
    }

    #[test]
    #[should_panic(expected = "topological_sort made no progress")]
    fn test_topological_sort_dangling_dep_panics() {
        // Graph references a package that isn't a key — previously caused an
        // infinite loop. Now the assert in `topological_sort` catches it.
        let mut dep_graph = HashMap::new();
        dep_graph.insert(Package::EspHal, vec![Package::EspAlloc]);
        let _ = topological_sort(&dep_graph);
    }

    #[test]
    fn test_change_detection() {
        let dep_graph = sample_dep_graph();
        let sorted = topological_sort(&dep_graph);

        let assert_changes = |changed: &[Package], expected: &[Package]| {
            let changed = collect_changed_packages(&sorted, &|p| dep_graph[&p].clone(), &|p| {
                changed.contains(&p)
            });
            let changed = changed
                .into_iter()
                .filter_map(|(p, ch)| if ch { Some(p) } else { None })
                .collect::<Vec<_>>();

            assert_unstable_lists_equal(&changed, expected);
        };

        assert_changes(&[], &[]);
        assert_changes(&[Package::EspRtos], &[Package::EspRtos]);
        assert_changes(&[Package::EspRadio], &[Package::EspRadio, Package::EspRtos]);
        assert_changes(
            &[Package::EspHal],
            &[Package::EspHal, Package::EspRadio, Package::EspRtos],
        );
    }
}
