//! Code generation tool for esp-metadata.
//!
//! Owns everything that is derived from `devices/*.toml`: the
//! `esp-metadata-generated` crate, the tables in the esp-hal README, and the
//! metadata cache consumed by the devtool.

use std::{
    collections::{BTreeMap, BTreeSet},
    path::{Path, PathBuf},
    process::Command,
    time::Duration,
};

use anyhow::{Context, Result, bail};
use esp_metadata::{Chip, Config, TokenStream};

/// Bump when the cache layout changes. Devtools that expect a different
/// version refuse to use the cache instead of regenerating it, because
/// regeneration cannot resolve a version mismatch.
const CACHE_VERSION: u32 = 1;

const USAGE: &str = "\
Usage: cargo update-metadata [--check]

Re-generates `esp-metadata-generated`, the tables in the esp-hal README, and
the metadata cache read by the devtool.

    --check    Exit with 1 if the generated code is not up to date.
";

fn main() -> Result<()> {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    let mut check = false;
    for arg in std::env::args().skip(1) {
        match arg.as_str() {
            "generate" => {}
            "--check" => check = true,
            _ => {
                eprint!("{USAGE}");
                bail!("Unrecognized argument: {arg}");
            }
        }
    }

    let workspace = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf();

    generate(&workspace, check)
}

fn generate(workspace: &Path, check: bool) -> Result<()> {
    // Generated code is only useful once formatted, so without rustfmt we
    // refresh the cache alone. This keeps the devtool usable in environments
    // that only build (CI jobs, for example), where regenerating would
    // otherwise fail every command that reads chip metadata.
    if !rustfmt_available() {
        if check {
            bail!("Checking the generated code needs `cargo +nightly fmt`, which is not available");
        }

        log::debug!("`cargo +nightly fmt` is not available, only refreshing the metadata cache");
        dump_cache(workspace)?;

        return Ok(());
    }

    log::info!("Updating esp-metadata-generated and README tables...");

    update_readme_tables(workspace)?;

    let out_path = workspace.join("esp-metadata-generated").join("src");
    for chip in Chip::iter() {
        log::info!("Generating metadata for {}", chip.pretty_name());
        let config = Config::for_chip(&chip);
        save(
            &out_path.join(format!("_generated_{chip}.rs")),
            config.generate_metadata(),
        )?;
    }
    save(
        &out_path.join("_build_script_utils.rs"),
        esp_metadata::generate_build_script_utils(),
    )?;
    save(&out_path.join("lib.rs"), esp_metadata::generate_lib_rs())?;

    format_generated_crate(workspace)?;

    // The cache is derived from the same inputs, so keep it in step.
    dump_cache(workspace)?;

    if check {
        let res = Command::new("git")
            .args(["diff", "HEAD", "esp-metadata-generated"])
            .current_dir(workspace)
            .output()
            .context("Failed to run `git diff HEAD esp-metadata-generated`")?;
        if !res.stdout.is_empty() {
            bail!(
                "detected `esp-metadata-generated` changes. Run `cargo update-metadata`, and commit the changes."
            );
        }
    }

    Ok(())
}

fn save(out_path: &Path, tokens: TokenStream) -> Result<()> {
    let source = tokens.to_string();

    let syntax_tree = syn::parse_file(&source)?;
    let mut source = String::from(
        "// Do NOT edit this file directly. Make your changes to esp-metadata,\n// then run `cargo update-metadata`.\n\n",
    );
    source.push_str(&prettyplease::unparse(&syntax_tree));

    write_file(out_path, source)
}

fn rustfmt_available() -> bool {
    Command::new("cargo")
        .args(["+nightly", "fmt", "--version"])
        .output()
        .is_ok_and(|output| output.status.success())
}

fn format_generated_crate(workspace: &Path) -> Result<()> {
    let package_path = workspace.join("esp-metadata-generated");

    let mut args = vec![
        String::from("+nightly"),
        String::from("fmt"),
        String::from("--"),
        format!(
            "--config-path={}",
            package_path.join("rustfmt.toml").display()
        ),
    ];
    for entry in walkdir::WalkDir::new(package_path.join("src")) {
        let path = entry?.into_path();
        if path.extension().is_some_and(|ext| ext == "rs") {
            args.push(path.display().to_string());
        }
    }

    retry_on_failure("Formatting esp-metadata-generated", || {
        let output = Command::new("cargo")
            .args(&args)
            .current_dir(&package_path)
            .output()
            .context("Failed to run `cargo fmt`")?;

        let stderr = String::from_utf8_lossy(&output.stderr);
        // rustfmt reports files it could not write without failing itself,
        // which would leave the generated code unformatted.
        if !output.status.success() || stderr.contains("Error writing files") {
            bail!("`cargo fmt` failed: {stderr}");
        }

        Ok(())
    })
}

fn update_readme_tables(workspace: &Path) -> Result<()> {
    const SUPPORTED_DEVICES_START: &str = "<!-- start supported devices table -->";
    const SUPPORTED_DEVICES_END: &str = "<!-- end supported devices table -->";
    const CHIP_SUPPORT_START: &str = "<!-- start chip support table -->";
    const CHIP_SUPPORT_END: &str = "<!-- end chip support table -->";

    log::debug!("Updating generated tables in README.md...");
    let readme_path = workspace.join("esp-hal").join("README.md");
    let readme = std::fs::read_to_string(&readme_path)
        .with_context(|| format!("Failed to read {}", readme_path.display()))?;

    let mut output = String::new();
    let mut end_marker = None;
    for line in readme.lines() {
        let trimmed = line.trim();

        if let Some(end) = end_marker {
            if trimmed == end {
                output.push_str(line);
                output.push('\n');
                end_marker = None;
            }
            continue;
        }

        output.push_str(line);
        output.push('\n');

        match trimmed {
            SUPPORTED_DEVICES_START => {
                esp_metadata::generate_supported_devices_table(&mut output)?;
                end_marker = Some(SUPPORTED_DEVICES_END);
            }
            CHIP_SUPPORT_START => {
                esp_metadata::generate_chip_support_status(&mut output)?;
                end_marker = Some(CHIP_SUPPORT_END);
            }
            _ => {}
        }
    }

    write_file(&readme_path, output)
}

#[derive(serde::Serialize)]
struct Cache {
    version: u32,
    hash: String,
    /// Every valueless symbol defined by any chip.
    symbols: Vec<String>,
    /// Every symbol with a value defined by any chip.
    kv_symbols: Vec<String>,
    chips: BTreeMap<String, ChipCache>,
}

#[derive(serde::Serialize)]
struct ChipCache {
    pretty_name: String,
    arch: String,
    target: String,
    // TOML has no null: an absent LP target is an absent key.
    #[serde(skip_serializing_if = "Option::is_none")]
    lp_target: Option<String>,
    has_lp_core: bool,
    symbols: Vec<String>,
    kv_values: BTreeMap<String, String>,
}

/// Symbols are used as variables in chip filter expressions, so those that
/// cannot be spelled as an identifier are dropped.
fn symbol_to_ident(symbol: &str) -> Option<String> {
    symbol
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.')
        .then_some(symbol.replace('.', "_"))
}

/// Splits a chip's symbols into valueless ones and `key="value"` ones.
fn split_symbols(config: &Config) -> (Vec<String>, BTreeMap<String, String>) {
    let mut symbols = vec![];
    let mut kv_values = BTreeMap::new();

    for symbol in config.all() {
        match symbol.split_once('=') {
            Some((key, value)) => {
                if let Some(key) = symbol_to_ident(key.trim()) {
                    kv_values.insert(key, value.trim().trim_matches('"').to_string());
                }
            }
            None => symbols.extend(symbol_to_ident(symbol)),
        }
    }

    (symbols, kv_values)
}

/// Write the devtool's metadata cache.
///
/// The cache deliberately only contains data the devtool queries, in a layout
/// that doesn't change when the shape of the metadata does: adding or renaming
/// a property only ever changes which symbols are listed. Symbols are stored in
/// the form the devtool evaluates them in, so it doesn't need to know how they
/// are spelled in the metadata.
fn dump_cache(workspace: &Path) -> Result<PathBuf> {
    let mut chips = BTreeMap::new();
    for chip in Chip::iter() {
        let config = Config::for_chip(&chip);
        let (symbols, kv_values) = split_symbols(config);
        chips.insert(
            chip.to_string(),
            ChipCache {
                pretty_name: chip.pretty_name().to_string(),
                arch: config.arch().to_string(),
                target: chip.target(),
                lp_target: chip.lp_target().ok().map(str::to_string),
                has_lp_core: chip.has_lp_core(),
                symbols,
                kv_values,
            },
        );
    }

    // A symbol that has a value on any chip is treated as having one
    // everywhere, so that it is never seeded as both a boolean and a string.
    let kv_symbols = chips
        .values()
        .flat_map(|chip| chip.kv_values.keys().cloned())
        .collect::<BTreeSet<_>>();
    let symbols = chips
        .values()
        .flat_map(|chip| chip.symbols.iter().cloned())
        .filter(|symbol| !kv_symbols.contains(symbol))
        .collect::<BTreeSet<_>>();

    let cache = Cache {
        version: CACHE_VERSION,
        hash: esp_metadata::input_hash(workspace)?,
        symbols: symbols.into_iter().collect(),
        kv_symbols: kv_symbols.into_iter().collect(),
        chips,
    };

    let path = esp_metadata::cache_path(workspace);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create {}", parent.display()))?;
    }

    // Written via a temporary file: a devtool invocation may be reading the
    // cache while another one refreshes it.
    let tmp = path.with_extension("toml.tmp");
    write_file(&tmp, toml::to_string_pretty(&cache)?)?;
    std::fs::rename(&tmp, &path).with_context(|| format!("Failed to write {}", path.display()))?;

    log::debug!("Wrote {}", path.display());

    Ok(path)
}

/// How many times an operation that writes files is attempted before giving up.
const WRITE_ATTEMPTS: usize = 5;

/// Runs `operation`, retrying up to [`WRITE_ATTEMPTS`] times.
///
/// Writing files can transiently fail if another process (an editor, a virus
/// scanner, ...) holds a lock on them, so give the lock a chance to disappear
/// before propagating the error.
fn retry_on_failure<T>(what: &str, mut operation: impl FnMut() -> Result<T>) -> Result<T> {
    for attempt in 1..=WRITE_ATTEMPTS {
        match operation() {
            Ok(value) => return Ok(value),
            Err(error) if attempt < WRITE_ATTEMPTS => {
                log::warn!("{what} failed (attempt {attempt}/{WRITE_ATTEMPTS}), retrying...");
                log::debug!("{error:?}");
                std::thread::sleep(Duration::from_millis(200 * attempt as u64));
            }
            Err(error) => return Err(error),
        }
    }

    unreachable!()
}

fn write_file(path: &Path, contents: impl AsRef<[u8]>) -> Result<()> {
    let contents = contents.as_ref();
    retry_on_failure(&format!("Writing {}", path.display()), || {
        std::fs::write(path, contents)
            .with_context(|| format!("Failed to write {}", path.display()))
    })
}
