//! Code generation tool for esp-metadata.
//!
//! Owns everything that is derived from `devices/*.toml`: the
//! `esp-metadata-generated` crate, the tables in the esp-hal README, and the
//! metadata cache consumed by the devtool.

use std::{
    collections::BTreeMap,
    path::{Path, PathBuf},
    process::Command,
    time::Duration,
};

use anyhow::{Context, Result, bail};
use clap::Parser;
use esp_metadata::{Chip, Config, TokenStream};
use strum::IntoEnumIterator;

/// Bump when the cache layout changes. Devtools that expect a different
/// version refuse to use the cache instead of regenerating it, because
/// regeneration cannot resolve a version mismatch.
const CACHE_VERSION: u32 = 1;

#[derive(Debug, Parser)]
enum Cli {
    /// Re-generate `esp-metadata-generated` and the tables in the esp-hal README.
    Generate(GenerateArgs),
    /// Write the metadata cache read by the devtool.
    DumpCache,
}

#[derive(Debug, clap::Args)]
struct GenerateArgs {
    /// Run in 'check' mode; exits with 0 if the generated code is up to date, 1 otherwise.
    #[arg(long)]
    check: bool,
}

fn main() -> Result<()> {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    let workspace = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf();

    match Cli::parse() {
        Cli::Generate(args) => generate(&workspace, args.check),
        Cli::DumpCache => dump_cache(&workspace).map(|_| ()),
    }
}

fn generate(workspace: &Path, check: bool) -> Result<()> {
    log::info!("Updating esp-metadata-generated and README tables...");

    update_readme_tables(workspace)?;

    let out_path = workspace.join("esp-metadata-generated").join("src");
    for chip in Chip::iter() {
        log::info!("Generating metadata for {}", chip.pretty_name());
        let config = Config::for_chip(&chip);
        save(
            &out_path.join(format!("_generated_{chip}.rs")),
            config.generate_metadata(),
        )?;
    }
    save(
        &out_path.join("_build_script_utils.rs"),
        esp_metadata::generate_build_script_utils(),
    )?;
    save(&out_path.join("lib.rs"), esp_metadata::generate_lib_rs())?;

    format_generated_crate(workspace)?;

    // The cache is derived from the same inputs, so keep it in step.
    dump_cache(workspace)?;

    if check {
        let res = Command::new("git")
            .args(["diff", "HEAD", "esp-metadata-generated"])
            .current_dir(workspace)
            .output()
            .context("Failed to run `git diff HEAD esp-metadata-generated`")?;
        if !res.stdout.is_empty() {
            bail!(
                "detected `esp-metadata-generated` changes. Run `cargo update-metadata`, and commit the changes."
            );
        }
    }

    Ok(())
}

fn save(out_path: &Path, tokens: TokenStream) -> Result<()> {
    let source = tokens.to_string();

    let syntax_tree = syn::parse_file(&source)?;
    let mut source = String::from(
        "// Do NOT edit this file directly. Make your changes to esp-metadata,\n// then run `cargo update-metadata`.\n\n",
    );
    source.push_str(&prettyplease::unparse(&syntax_tree));

    write_file(out_path, source)
}

fn format_generated_crate(workspace: &Path) -> Result<()> {
    let package_path = workspace.join("esp-metadata-generated");

    let mut args = vec![
        String::from("+nightly"),
        String::from("fmt"),
        String::from("--"),
        format!("--config-path={}", package_path.join("rustfmt.toml").display()),
    ];
    for entry in walkdir::WalkDir::new(package_path.join("src")) {
        let path = entry?.into_path();
        if path.extension().is_some_and(|ext| ext == "rs") {
            args.push(path.display().to_string());
        }
    }

    retry_on_failure("Formatting esp-metadata-generated", || {
        let status = Command::new("cargo")
            .args(&args)
            .current_dir(&package_path)
            .status()
            .context("Failed to run `cargo fmt`")?;
        if !status.success() {
            bail!("`cargo fmt` failed with {status}");
        }
        Ok(())
    })
}

fn update_readme_tables(workspace: &Path) -> Result<()> {
    const SUPPORTED_DEVICES_START: &str = "<!-- start supported devices table -->";
    const SUPPORTED_DEVICES_END: &str = "<!-- end supported devices table -->";
    const CHIP_SUPPORT_START: &str = "<!-- start chip support table -->";
    const CHIP_SUPPORT_END: &str = "<!-- end chip support table -->";

    log::debug!("Updating generated tables in README.md...");
    let readme_path = workspace.join("esp-hal").join("README.md");
    let readme = std::fs::read_to_string(&readme_path)
        .with_context(|| format!("Failed to read {}", readme_path.display()))?;

    let mut output = String::new();
    let mut end_marker = None;
    for line in readme.lines() {
        let trimmed = line.trim();

        if let Some(end) = end_marker {
            if trimmed == end {
                output.push_str(line);
                output.push('\n');
                end_marker = None;
            }
            continue;
        }

        output.push_str(line);
        output.push('\n');

        match trimmed {
            SUPPORTED_DEVICES_START => {
                esp_metadata::generate_supported_devices_table(&mut output)?;
                end_marker = Some(SUPPORTED_DEVICES_END);
            }
            CHIP_SUPPORT_START => {
                esp_metadata::generate_chip_support_status(&mut output)?;
                end_marker = Some(CHIP_SUPPORT_END);
            }
            _ => {}
        }
    }

    write_file(&readme_path, output)
}

#[derive(serde::Serialize)]
struct Cache {
    version: u32,
    hash: String,
    chips: BTreeMap<String, ChipCache>,
}

#[derive(serde::Serialize)]
struct ChipCache {
    target: String,
    symbols: Vec<String>,
}

/// Write the devtool's metadata cache.
///
/// The cache deliberately only contains data the devtool queries, in a layout
/// that doesn't change when the shape of the metadata does: adding or renaming
/// a property only ever changes the contents of `symbols`.
fn dump_cache(workspace: &Path) -> Result<PathBuf> {
    let mut chips = BTreeMap::new();
    for chip in Chip::iter() {
        chips.insert(
            chip.to_string(),
            ChipCache {
                target: chip.target(),
                symbols: Config::for_chip(&chip).all().to_vec(),
            },
        );
    }

    let cache = Cache {
        version: CACHE_VERSION,
        hash: esp_metadata::input_hash(workspace)?,
        chips,
    };

    let path = esp_metadata::cache_path(workspace);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create {}", parent.display()))?;
    }

    // Written via a temporary file: a devtool invocation may be reading the
    // cache while another one refreshes it.
    let tmp = path.with_extension("json.tmp");
    write_file(&tmp, serde_json::to_vec_pretty(&cache)?)?;
    std::fs::rename(&tmp, &path)
        .with_context(|| format!("Failed to write {}", path.display()))?;

    log::debug!("Wrote {}", path.display());

    Ok(path)
}

/// How many times an operation that writes files is attempted before giving up.
const WRITE_ATTEMPTS: usize = 5;

/// Runs `operation`, retrying up to [`WRITE_ATTEMPTS`] times.
///
/// Writing files can transiently fail if another process (an editor, a virus
/// scanner, ...) holds a lock on them, so give the lock a chance to disappear
/// before propagating the error.
fn retry_on_failure<T>(what: &str, mut operation: impl FnMut() -> Result<T>) -> Result<T> {
    for attempt in 1..=WRITE_ATTEMPTS {
        match operation() {
            Ok(value) => return Ok(value),
            Err(error) if attempt < WRITE_ATTEMPTS => {
                log::warn!("{what} failed (attempt {attempt}/{WRITE_ATTEMPTS}), retrying...");
                log::debug!("{error:?}");
                std::thread::sleep(Duration::from_millis(200 * attempt as u64));
            }
            Err(error) => return Err(error),
        }
    }

    unreachable!()
}

fn write_file(path: &Path, contents: impl AsRef<[u8]>) -> Result<()> {
    let contents = contents.as_ref();
    retry_on_failure(&format!("Writing {}", path.display()), || {
        std::fs::write(path, contents)
            .with_context(|| format!("Failed to write {}", path.display()))
    })
}
