system_clocks = { clock_tree = [
    { name = "XTAL_CLK",    type = "source",                     values = "40",                         output = "VALUE * 1_000_000", always_on = true },
    { name = "PLL_CLK",     type = "derived", from = "XTAL_CLK", values = "320, 480",                   output = "VALUE * 1_000_000" }, # TODO reject = "VALUE == 320_000_000 && CPU_PLL_DIV_OUT == 240_000_000"
    { name = "APLL_CLK",    type = "derived", from = "PLL_CLK",  values = "16_000_000 ..= 128_000_000", output = "VALUE" },
    { name = "RC_FAST_CLK", type = "source",  output = "8_000_000" }, # this is supposed to be adjustable using RTC_CNTL_CK8M_DIV_SEL

    # Represents SEL0 = 1, 3
    { name = "CPU_PLL_DIV_IN", type = "mux", variants = [
        { name = "PLL",  outputs = "PLL_CLK" },
        { name = "APLL", outputs = "APLL_CLK" },
    ] },
    { name = "CPU_PLL_DIV", type = "generic", params = { divisor = "2, 3, 4, 6" }, output = "CPU_PLL_DIV_IN / divisor" }, # TODO reject = "PLL_CLK == 320_000_000 && divisor % 3 == 0"

    # Represents SEL0 = 0, 2
    { name = "SYSTEM_PRE_DIV_IN", type = "mux", variants = [
        { name = "XTAL",    outputs = "XTAL_CLK" },
        { name = "RC_FAST", outputs = "RC_FAST_CLK" },
    ] },
    { name = "SYSTEM_PRE_DIV", type = "generic", params = { divisor = "0 .. 1024" }, output = "SYSTEM_PRE_DIV_IN / (divisor + 1)" },

    # The meta-switch
    { name = "CPU_CLK", type = "mux", always_on = true, variants = [
        # source clock      CPU clock                   additional config (mux = variant name, divider = divisor expression)
        { name = "XTAL",    outputs = "SYSTEM_PRE_DIV", configures = [ "SYSTEM_PRE_DIV_IN = XTAL",    "APB_CLK = XTAL",     "REF_TICK = XTAL",    "REF_TICK_XTAL = XTAL_CLK / 1_000_000 - 1" ] },
        { name = "RC_FAST", outputs = "SYSTEM_PRE_DIV", configures = [ "SYSTEM_PRE_DIV_IN = RC_FAST", "APB_CLK = RC_FAST",  "REF_TICK = RC_FAST", "REF_TICK_CK8M = RC_FAST_CLK / 1_000_000 - 1" ] },
        { name = "APLL",    outputs = "CPU_PLL_DIV",    configures = [ "CPU_PLL_DIV_IN = APLL",       "APB_CLK = APLL",     "REF_TICK = APLL",    "REF_TICK_XTAL = XTAL_CLK / 1_000_000 - 1" ] },
        { name = "PLL",     outputs = "CPU_PLL_DIV",    configures = [ "CPU_PLL_DIV_IN = PLL",        "APB_CLK = PLL",      "REF_TICK = PLL",     "REF_TICK_XTAL = XTAL_CLK / 1_000_000 - 1" ] },
    ] },

    # APB options
    { name = "APB_CLK_CPU_DIV2", type = "generic", output = "CPU_CLK / 2" },
    { name = "APB_CLK_80M",      type = "derived", from = "CPU_CLK", output = "80_000_000" },
    { name = "APB_CLK", type = "mux", variants = [
        { name = "PLL",     outputs = "APB_CLK_80M" },
        { name = "APLL",    outputs = "APB_CLK_CPU_DIV2" },
        { name = "XTAL",    outputs = "CPU_CLK" },
        { name = "RC_FAST", outputs = "CPU_CLK" },
    ] },

    # REF_TICK, configuring CPU clock needs to ensure this is 1MHz
    { name = "REF_TICK_XTAL", type = "generic", params = { divisor = "0 .. 256" }, output = "XTAL_CLK / (divisor + 1)" },
    { name = "REF_TICK_CK8M", type = "generic", params = { divisor = "0 .. 256" }, output = "RC_FAST_CLK / (divisor + 1)" },
    { name = "REF_TICK", type = "mux", variants = [
        { name = "PLL",     outputs = "REF_TICK_XTAL" },
        { name = "APLL",    outputs = "REF_TICK_XTAL" },
        { name = "XTAL",    outputs = "REF_TICK_XTAL" },
        { name = "RC_FAST", outputs = "REF_TICK_CK8M" },
    ] },

    # Low-speed clocks
    { name = "XTAL32K_CLK",     type = "source",  output = "32768" },
    { name = "RC_SLOW_CLK",     type = "source",  output = "90_000" },
    { name = "RC_FAST_DIV_CLK", type = "generic", output = "RC_FAST_CLK / 256" },
    { name = "XTAL_DIV_CLK",    type = "generic", output = "XTAL_CLK / 4" }, # source: esp-idf SOC_RTC_FAST_CLK_SRC_XTAL_D4

    { name = "RTC_SLOW_CLK", type = "mux", variants = [
        { name = "XTAL32K",    outputs = "XTAL32K_CLK" },
        { name = "RC_SLOW", outputs = "RC_SLOW_CLK" },
        { name = "RC_FAST", outputs = "RC_FAST_DIV_CLK" },
    ] },
    { name = "RTC_FAST_CLK", type = "mux", variants = [
        { name = "XTAL", outputs = "XTAL_DIV_CLK" },
        { name = "RC",   outputs = "RC_FAST_CLK" },
    ] },

    # System-wide peripheral clocks
    { name = "UART_MEM_CLK", type = "mux", variants = [
        # The actual source clock is unknown, but it also doesn't matter.
        { name = "XTAL", outputs = "XTAL_CLK", default = true },
    ] },

    # There are separate clock muxes for each TIMG instance, but esp-hal only uses one. Only modelling
    # one makes the HAL code simpler.
    { name = "TIMG_CALIBRATION_CLOCK", type = "mux", variants = [
        { name = "RTC_CLK",         outputs = "RTC_SLOW_CLK" },
        { name = "RC_FAST_DIV_CLK", outputs = "RC_FAST_DIV_CLK" },
        { name = "XTAL32K_CLK",     outputs = "XTAL32K_CLK" },
    ] },
], template_groups = [
    { group = "TIMG", clocks = [
        { name = "FUNCTION_CLOCK", type = "mux", variants = [
            { name = "XTAL_CLK", outputs = "XTAL_CLK", default = true },
            { name = "APB_CLK",  outputs = "APB_CLK" },
        ] },
    ] },
    { group = "UART", clocks = [
        { name = "FUNCTION_CLOCK", type = "generic", output = "sclk", params = { sclk = [
            { name = "APB",      outputs = "APB_CLK", default = true },
            { name = "REF_TICK", outputs = "REF_TICK" }
        ] } },
        { name = "BAUD_RATE_GENERATOR", type = "generic", output = "(FUNCTION_CLOCK * 16) / (integral * 16 + fractional)", params = { fractional = "0..16", integral = "0..0x100000" } },
        { name = "MEM_CLOCK", type = "generic", output = "UART_MEM_CLK" },
    ] },
    { group = "RMT", clocks = [
        { name = "SCLK", type = "mux", variants = [
            { name = "REF_TICK", outputs = "REF_TICK" },
            { name = "APB_CLK",  outputs = "APB_CLK", default = true },
        ] },
    ] },
    { group = "I2C", clocks = [
        { name = "FUNCTION_CLOCK", type = "generic", output = "sclk", params = { sclk = [
            { name = "APB",      outputs = "APB_CLK", default = true },
            { name = "REF_TICK", outputs = "REF_TICK" },
        ] } },
    ] },
    { group = "SPI", clocks = [
        { name = "FUNCTION_CLOCK", type = "mux", variants = [
            { name = "APB", outputs = "APB_CLK", default = true },
        ] },
    ] },
] }

peripheral_clocks = { templates = [
    # templates
    { name = "clk_en_template", value = "{{control}}::regs().{{clk_en_register}}().modify(|_, w| w.{{clk_en_field}}().bit(enable));" },
    { name = "rst_template", value = "{{control}}::regs().{{rst_register}}().modify(|_, w| w.{{rst_field}}().bit(reset));" },
    # substitutions
    { name = "control", value = "crate::peripherals::SYSTEM" },
    { name = "reg_group", value = "en0" },
    { name = "clk_en_register", value = "perip_clk_{{reg_group}}" },
    { name = "clk_en_field", value = "{{peripheral}}_clk_en" },
    { name = "rst_register", value = "perip_rst_{{reg_group}}" },
    { name = "rst_field", value = "{{peripheral}}_rst" },
], peripheral_clocks = [
    { name = "Aes", template_params = { reg_group = "en1", peripheral = "crypto_aes" } },
    { name = "Rsa", template_params = { reg_group = "en1", peripheral = "crypto_rsa" } },
    { name = "Sha", template_params = { reg_group = "en1", peripheral = "crypto_sha" } },
    { name = "Ds", template_params = { reg_group = "en1", peripheral = "crypto_ds" } },
    { name = "Hmac", template_params = { reg_group = "en1", peripheral = "crypto_hmac" } },
    { name = "CryptoDma", template_params = { reg_group = "en1" } },
    
    # The exception: CopyDma needs to be enabled in its own register space and its reset is a bit gnarly
    { name = "CopyDma", template_params = { clk_en_template = "crate::peripherals::DMA_COPY::regs().conf().modify(|_, w| w.clk_en().bit(enable));", rst_template = "crate::peripherals::DMA_COPY::regs().conf().modify(|_, w| { w.in_rst().bit(reset).out_rst().bit(reset).cmdfifo_rst().bit(reset).fifo_rst().bit(reset) });" } },
    { name = "DedicatedGpio", template_params = { clk_en_register = "cpu_peri_clk_en", rst_register = "cpu_peri_rst_en" } },

    #{ name = "Adc2Arb" },
    { name = "Systimer", keep_enabled = true },
    { name = "ApbSarAdc", template_params = { peripheral = "apb_saradc" } },
    { name = "Spi3Dma" },
    #{ name = "Pwm3" },
    #{ name = "Pwm2" },
    { name = "UartMem", keep_enabled = true }, # TODO: keep_enabled can be removed once esp-println needs explicit initialization
    { name = "UsbFs", template_params = { peripheral = "usb" } },
    { name = "Spi2Dma" },
    { name = "Mcpwm1", template_params = { peripheral = "pwm1" } },
    { name = "Twai0", template_params = { peripheral = "twai" } },
    { name = "I2cExt1" },
    { name = "Mcpwm0", template_params = { peripheral = "pwm0" } },
    { name = "Spi3" },
    { name = "Timg1", template_params = { peripheral = "timergroup1" } },
    #{ name = "Efuse" },
    { name = "Timg0", template_params = { peripheral = "timergroup" }, keep_enabled = true },
    { name = "Uhci1" },
    { name = "Ledc" },
    { name = "Pcnt" },
    { name = "Rmt" },
    { name = "Uhci0" },
    { name = "I2cExt0" },
    { name = "Spi2" },
    { name = "Uart1" },
    { name = "I2s0" },
    { name = "Wdg" },
    { name = "Uart0", template_params = { peripheral = "uart" }, keep_enabled = true },
    #{ name = "Spi01" },
    #{ name = "Timers" },
    
    # Radio clocks not modeled here.
] }
