version = 2
has_input_sync = true
gpio_function = 1
constant_0_input = 0x3c
constant_1_input = 0x38
pins = [
    { pin =  0,                                                                                                               rtc = { 0 = "RTC_GPIO0"  }, limitations = ["strapping"] },
    { pin =  1,                                                                analog = { 0 = "TOUCH1",     1 = "ADC1_CH0" }, rtc = { 0 = "RTC_GPIO1"  } },
    { pin =  2,                                                                analog = { 0 = "TOUCH2",     1 = "ADC1_CH1" }, rtc = { 0 = "RTC_GPIO2"  } },
    { pin =  3,                                                                analog = { 0 = "TOUCH3",     1 = "ADC1_CH2" }, rtc = { 0 = "RTC_GPIO3"  } },
    { pin =  4,                                                                analog = { 0 = "TOUCH4",     1 = "ADC1_CH3" }, rtc = { 0 = "RTC_GPIO4"  } },
    { pin =  5,                                                                analog = { 0 = "TOUCH5",     1 = "ADC1_CH4" }, rtc = { 0 = "RTC_GPIO5"  } },
    { pin =  6,                                                                analog = { 0 = "TOUCH6",     1 = "ADC1_CH5" }, rtc = { 0 = "RTC_GPIO6"  } },
    { pin =  7,                                                                analog = { 0 = "TOUCH7",     1 = "ADC1_CH6" }, rtc = { 0 = "RTC_GPIO7"  } },
    { pin =  8, functions = {                3 = "SUBSPICS1"                }, analog = { 0 = "TOUCH8",     1 = "ADC1_CH7" }, rtc = { 0 = "RTC_GPIO8"  } },
    { pin =  9, functions = {                3 = "SUBSPIHD",  4 = "FSPIHD"  }, analog = { 0 = "TOUCH9",     1 = "ADC1_CH8" }, rtc = { 0 = "RTC_GPIO9"  } },
    { pin = 10, functions = { 2 = "FSPIIO4", 3 = "SUBSPICS0", 4 = "FSPICS0" }, analog = { 0 = "TOUCH10",    1 = "ADC1_CH9" }, rtc = { 0 = "RTC_GPIO10" } },
    { pin = 11, functions = { 2 = "FSPIIO5", 3 = "SUBSPID",   4 = "FSPID"   }, analog = { 0 = "TOUCH11",    1 = "ADC2_CH0" }, rtc = { 0 = "RTC_GPIO11" } },
    { pin = 12, functions = { 2 = "FSPIIO6", 3 = "SUBSPICLK", 4 = "FSPICLK" }, analog = { 0 = "TOUCH12",    1 = "ADC2_CH1" }, rtc = { 0 = "RTC_GPIO12" } },
    { pin = 13, functions = { 2 = "FSPIIO7", 3 = "SUBSPIQ",   4 = "FSPIQ"   }, analog = { 0 = "TOUCH13",    1 = "ADC2_CH2" }, rtc = { 0 = "RTC_GPIO13" } },
    { pin = 14, functions = { 2 = "FSPIDQS", 3 = "SUBSPIWP",  4 = "FSPIWP"  }, analog = { 0 = "TOUCH14",    1 = "ADC2_CH3" }, rtc = { 0 = "RTC_GPIO14" } },
    { pin = 15, functions = { 2 = "U0RTS" },                                   analog = { 0 = "XTAL_32K_P", 1 = "ADC2_CH4" }, rtc = { 0 = "RTC_GPIO15" } },
    { pin = 16, functions = { 2 = "U0CTS" },                                   analog = { 0 = "XTAL_32K_N", 1 = "ADC2_CH5" }, rtc = { 0 = "RTC_GPIO16" } },
    { pin = 17, functions = { 2 = "U1TXD" },                                   analog = { 0 = "DAC_1",      1 = "ADC2_CH6" }, rtc = { 0 = "RTC_GPIO17" } },
    { pin = 18, functions = { 2 = "U1RXD",   3 = "CLK_OUT3" },                 analog = { 0 = "DAC_2",      1 = "ADC2_CH7" }, rtc = { 0 = "RTC_GPIO18" } },
    { pin = 19, functions = { 2 = "U1RTS",   3 = "CLK_OUT2" },                 analog = { 0 = "USB_FS_DM",  1 = "ADC2_CH8" }, rtc = { 0 = "RTC_GPIO19" } },
    { pin = 20, functions = { 2 = "U1CTS",   3 = "CLK_OUT1" },                 analog = { 0 = "USB_FS_DP",  1 = "ADC2_CH9" }, rtc = { 0 = "RTC_GPIO20" } },
    { pin = 21,                                                                                                               rtc = { 0 = "RTC_GPIO21" } },

    { pin = 26, functions = { 0 = "SPICS1" },                                             limitations = ["spi_psram"] },
    { pin = 27, functions = { 0 = "SPIHD"  },                                             limitations = ["spi_flash", "spi_psram"] },
    { pin = 28, functions = { 0 = "SPIWP"  },                                             limitations = ["spi_flash", "spi_psram"] },
    { pin = 29, functions = { 0 = "SPICS0" },                                             limitations = ["spi_flash"] },
    { pin = 30, functions = { 0 = "SPICLK" },                                             limitations = ["spi_flash", "spi_psram"] },
    { pin = 31, functions = { 0 = "SPIQ"   },                                             limitations = ["spi_flash", "spi_psram"] },
    { pin = 32, functions = { 0 = "SPID"   },                                             limitations = ["spi_flash", "spi_psram"] },
    { pin = 33, functions = {              2 = "FSPIHD",   3 = "SUBSPIHD"              }, limitations = ["octal_flash", "octal_psram"] },
    { pin = 34, functions = {              2 = "FSPICS0",  3 = "SUBSPICS0"             }, limitations = ["octal_flash", "octal_psram"] },
    { pin = 35, functions = {              2 = "FSPID",    3 = "SUBSPID"               }, limitations = ["octal_flash", "octal_psram"] },
    { pin = 36, functions = {              2 = "FSPICLK",  3 = "SUBSPICLK"             }, limitations = ["octal_flash", "octal_psram"] },
    { pin = 37, functions = {              2 = "FSPIQ",    3 = "SUBSPIQ", 4 = "SPIDQS" }, limitations = ["octal_flash", "octal_psram"] },
    { pin = 38, functions = {              2 = "FSPIWP",   3 = "SUBSPIWP"              } },
    { pin = 39, functions = { 0 = "MTCK",  2 = "CLK_OUT3", 3 = "SUBSPICS1" } },
    { pin = 40, functions = { 0 = "MTDO",  2 = "CLK_OUT2" } },
    { pin = 41, functions = { 0 = "MTDI",  2 = "CLK_OUT1" } },
    { pin = 42, functions = { 0 = "MTMS" } },
    { pin = 43, functions = { 0 = "U0TXD", 2 = "CLK_OUT1" } },
    { pin = 44, functions = { 0 = "U0RXD", 2 = "CLK_OUT2" } },
    { pin = 45, limitations = ["strapping"] },
    { pin = 46, limitations = ["strapping"] },
]
input_signals = [
    { name = "SPIQ",              id = 0 },
    { name = "SPID",              id = 1 },
    { name = "SPIHD",             id = 2 },
    { name = "SPIWP",             id = 3 },
    { name = "SPID4",             id = 7 },
    { name = "SPID5",             id = 8 },
    { name = "SPID6",             id = 9 },
    { name = "SPID7",             id = 10 },
    { name = "SPIDQS",            id = 11 },
    { name = "U0RXD",             id = 14 },
    { name = "U0CTS",             id = 15 },
    { name = "U0DSR",             id = 16 },
    { name = "U1RXD",             id = 17 },
    { name = "U1CTS",             id = 18 },
    { name = "U1DSR",             id = 21 },
    { name = "I2S0O_BCK",         id = 23 },
    { name = "I2S0O_WS",          id = 25 },
    { name = "I2S0I_BCK",         id = 27 },
    { name = "I2S0I_WS",          id = 28 },
    { name = "I2CEXT0_SCL",       id = 29 },
    { name = "I2CEXT0_SDA",       id = 30 },
    { name = "PCNT0_SIG_CH0",     id = 39 },
    { name = "PCNT0_SIG_CH1",     id = 40 },
    { name = "PCNT0_CTRL_CH0",    id = 41 },
    { name = "PCNT0_CTRL_CH1",    id = 42 },
    { name = "PCNT1_SIG_CH0",     id = 43 },
    { name = "PCNT1_SIG_CH1",     id = 44 },
    { name = "PCNT1_CTRL_CH0",    id = 45 },
    { name = "PCNT1_CTRL_CH1",    id = 46 },
    { name = "PCNT2_SIG_CH0",     id = 47 },
    { name = "PCNT2_SIG_CH1",     id = 48 },
    { name = "PCNT2_CTRL_CH0",    id = 49 },
    { name = "PCNT2_CTRL_CH1",    id = 50 },
    { name = "PCNT3_SIG_CH0",     id = 51 },
    { name = "PCNT3_SIG_CH1",     id = 52 },
    { name = "PCNT3_CTRL_CH0",    id = 53 },
    { name = "PCNT3_CTRL_CH1",    id = 54 },
    { name = "USB_EXTPHY_VP",     id = 61 },
    { name = "USB_EXTPHY_VM",     id = 62 },
    { name = "USB_EXTPHY_RCV",    id = 63 },
    { name = "USB_FS_IDDIG",      id = 64 },
    { name = "USB_FS_AVALID",     id = 65 },
    { name = "USB_FS_SRP_BVALID", id = 66 },
    { name = "USB_FS_VBUSVALID",  id = 67 },
    { name = "USB_SRP_SESSEND",   id = 68 },
    { name = "SPI3_CLK",          id = 72 },
    { name = "SPI3_Q",            id = 73 },
    { name = "SPI3_D",            id = 74 },
    { name = "SPI3_HD",           id = 75 },
    { name = "SPI3_CS0",          id = 76 },
    { name = "RMT_SIG_0",         id = 83 },
    { name = "RMT_SIG_1",         id = 84 },
    { name = "RMT_SIG_2",         id = 85 },
    { name = "RMT_SIG_3",         id = 86 },
    { name = "I2CEXT1_SCL",       id = 95 },
    { name = "I2CEXT1_SDA",       id = 96 },
    { name = "FSPICLK",           id = 108 },
    { name = "FSPIQ",             id = 109 },
    { name = "FSPID",             id = 110 },
    { name = "FSPIHD",            id = 111 },
    { name = "FSPIWP",            id = 112 },
    { name = "FSPIIO4",           id = 113 },
    { name = "FSPIIO5",           id = 114 },
    { name = "FSPIIO6",           id = 115 },
    { name = "FSPIIO7",           id = 116 },
    { name = "FSPICS0",           id = 117 },
    { name = "TWAI_RX",           id = 123 },
    { name = "SUBSPIQ",           id = 127 },
    { name = "SUBSPID",           id = 128 },
    { name = "SUBSPIHD",          id = 129 },
    { name = "SUBSPIWP",          id = 130 },
    { name = "I2S0I_DATA_IN15",   id = 158 },
    { name = "SUBSPID4",          id = 167 },
    { name = "SUBSPID5",          id = 168 },
    { name = "SUBSPID6",          id = 169 },
    { name = "SUBSPID7",          id = 170 },
    { name = "SUBSPIDQS",         id = 171 },
    { name = "PCMFSYNC",          id = 203 },
    { name = "PCMCLK",            id = 204 },

    { name = "PRO_ALONEGPIO0",    id = 235 },
    { name = "PRO_ALONEGPIO1",    id = 236 },
    { name = "PRO_ALONEGPIO2",    id = 237 },
    { name = "PRO_ALONEGPIO3",    id = 238 },
    { name = "PRO_ALONEGPIO4",    id = 239 },
    { name = "PRO_ALONEGPIO5",    id = 240 },
    { name = "PRO_ALONEGPIO6",    id = 241 },
    { name = "PRO_ALONEGPIO7",    id = 242 },

    { name = "MTDI" },
    { name = "MTCK" },
    { name = "MTMS" },
]
output_signals = [
    { name = "SPIQ",             id = 0 },
    { name = "SPID",             id = 1 },
    { name = "SPIHD",            id = 2 },
    { name = "SPIWP",            id = 3 },
    { name = "SPICLK",           id = 4 },
    { name = "SPICS0",           id = 5 },
    { name = "SPICS1",           id = 6 },
    { name = "SPID4",            id = 7 },
    { name = "SPID5",            id = 8 },
    { name = "SPID6",            id = 9 },
    { name = "SPID7",            id = 10 },
    { name = "SPIDQS",           id = 11 },
    { name = "U0TXD",            id = 14 },
    { name = "U0RTS",            id = 15 },
    { name = "U0DTR",            id = 16 },
    { name = "U1TXD",            id = 17 },
    { name = "U1RTS",            id = 18 },
    { name = "U1DTR",            id = 21 },
    { name = "I2S0O_BCK",        id = 23 },
    { name = "I2S0O_WS",         id = 25 },
    { name = "I2S0I_BCK",        id = 27 },
    { name = "I2S0I_WS",         id = 28 },
    { name = "I2CEXT0_SCL",      id = 29 },
    { name = "I2CEXT0_SDA",      id = 30 },
    { name = "SDIO_TOHOST_INT",  id = 31 },
    { name = "USB_EXTPHY_OEN",   id = 61 },
    { name = "USB_EXTPHY_VPO",   id = 63 },
    { name = "USB_EXTPHY_VMO",   id = 64 },
    { name = "SPI3_CLK",         id = 72 },
    { name = "SPI3_Q",           id = 73 },
    { name = "SPI3_D",           id = 74 },
    { name = "SPI3_HD",          id = 75 },
    { name = "SPI3_CS0",         id = 76 },
    { name = "SPI3_CS1",         id = 77 },
    { name = "SPI3_CS2",         id = 78 },
    { name = "LEDC_LS_SIG0",     id = 79 },
    { name = "LEDC_LS_SIG1",     id = 80 },
    { name = "LEDC_LS_SIG2",     id = 81 },
    { name = "LEDC_LS_SIG3",     id = 82 },
    { name = "LEDC_LS_SIG4",     id = 83 },
    { name = "LEDC_LS_SIG5",     id = 84 },
    { name = "LEDC_LS_SIG6",     id = 85 },
    { name = "LEDC_LS_SIG7",     id = 86 },
    { name = "RMT_SIG_0",        id = 87 },
    { name = "RMT_SIG_1",        id = 88 },
    { name = "RMT_SIG_2",        id = 89 },
    { name = "RMT_SIG_3",        id = 90 },
    { name = "I2CEXT1_SCL",      id = 95 },
    { name = "I2CEXT1_SDA",      id = 96 },
    { name = "GPIO_SD0",         id = 100 },
    { name = "GPIO_SD1",         id = 101 },
    { name = "GPIO_SD2",         id = 102 },
    { name = "GPIO_SD3",         id = 103 },
    { name = "GPIO_SD4",         id = 104 },
    { name = "GPIO_SD5",         id = 105 },
    { name = "GPIO_SD6",         id = 106 },
    { name = "GPIO_SD7",         id = 107 },
    { name = "FSPICLK",          id = 108 },
    { name = "FSPIQ",            id = 109 },
    { name = "FSPID",            id = 110 },
    { name = "FSPIHD",           id = 111 },
    { name = "FSPIWP",           id = 112 },
    { name = "FSPIIO4",          id = 113 },
    { name = "FSPIIO5",          id = 114 },
    { name = "FSPIIO6",          id = 115 },
    { name = "FSPIIO7",          id = 116 },
    { name = "FSPICS0",          id = 117 },
    { name = "FSPICS1",          id = 118 },
    { name = "FSPICS2",          id = 119 },
    { name = "FSPICS3",          id = 120 },
    { name = "FSPICS4",          id = 121 },
    { name = "FSPICS5",          id = 122 },
    { name = "TWAI_TX",          id = 123 },
    { name = "SUBSPICLK",        id = 126 },
    { name = "SUBSPIQ",          id = 127 },
    { name = "SUBSPID",          id = 128 },
    { name = "SUBSPIHD",         id = 129 },
    { name = "SUBSPIWP",         id = 130 },
    { name = "SUBSPICS0",        id = 131 },
    { name = "SUBSPICS1",        id = 132 },
    { name = "FSPIDQS",          id = 133 },
    { name = "FSPI_HSYNC",       id = 134 },
    { name = "FSPI_VSYNC",       id = 135 },
    { name = "FSPI_DE",          id = 136 },
    { name = "FSPICD",           id = 137 },
    { name = "SPI3_CD",          id = 139 },
    { name = "SPI3_DQS",         id = 140 },
    { name = "I2S0O_DATA_OUT23", id = 166 },
    { name = "SUBSPID4",         id = 167 },
    { name = "SUBSPID5",         id = 168 },
    { name = "SUBSPID6",         id = 169 },
    { name = "SUBSPID7",         id = 170 },
    { name = "SUBSPIDQS",        id = 171 },
    { name = "PCMFSYNC",         id = 209 },
    { name = "PCMCLK",           id = 210 },

    { name = "PRO_ALONEGPIO0",   id = 235 },
    { name = "PRO_ALONEGPIO1",   id = 236 },
    { name = "PRO_ALONEGPIO2",   id = 237 },
    { name = "PRO_ALONEGPIO3",   id = 238 },
    { name = "PRO_ALONEGPIO4",   id = 239 },
    { name = "PRO_ALONEGPIO5",   id = 240 },
    { name = "PRO_ALONEGPIO6",   id = 241 },
    { name = "PRO_ALONEGPIO7",   id = 242 },

    { name = "CLK_I2S",          id = 251 },

    { name = "GPIO",             id = 256 },

    { name = "CLK_OUT1" },
    { name = "CLK_OUT2" },
    { name = "CLK_OUT3" },

    { name = "MTDO" },
]
