# ESP32-C61 Device Metadata
#
# Empty [`device.driver`] tables imply `partial` support status.
#
# If you modify a driver support status, run `cargo xtask update-metadata` to
# update the table in the esp-hal README.

[device]
name   = "esp32c61"
arch   = "riscv"
target = "riscv32imac-unknown-none-elf"
cores  = 1
trm    = "https://www.espressif.com/sites/default/files/documentation/esp32-c61_technical_reference_manual_en.pdf"

symbols = [
    "swd",
    # ROM capabilities (TODO: verify against esp-idf when implementing)
    "rom_crc_le",
    "rom_crc_be",
    "rom_md5_bsd",
]

[device.soc]
cpu_has_csr_pc = true # TODO: VERIFY
cpu_has_prv_mode = true # TODO
rc_fast_clk_default = 17_500_000

memory_map = { ranges = [
    { name = "dram", start = 0x4080_0000, end = 0x4085_0000 },
    # start address from correct bootloader commit: https://github.com/espressif/esp-idf/blob/d66ebb8/components/bootloader/subproject/main/ld/esp32c61/bootloader.ld#L32
    { name = "dram2_uninit", start = 0x4083_EA70, end = 0x4084_EA70 },
] }

peripherals = [
    { name = "ASSIST_DEBUG"},
    { name = "CLINT" },
    # { name = "CPU_APM" }, # TODO: verify we need it
    { name = "DMA" },
    { name = "ECC" },
    { name = "ECDSA" },
    { name = "EFUSE" },
    { name = "ETM", pac = "SOC_ETM" },
    # { name = "GPIO" },
    # { name = "GPIO_SD", pac = "GPIO_EXT" },
    # { name = "HINF" }, # TODO: add PAC manually later
    { name = "HP_APM" },
    { name = "HP_SYS" },
    { name = "I2C_ANA_MST" },
    { name = "I2C0", interrupts = { peri = "I2C_EXT0" } },
    { name = "I2S0", interrupts = { peri = "I2S0" } },
    # { name = "IEEE802154" }, # TODO: add PAC manually later
    { name = "INTERRUPT_CORE0" },
    { name = "INTPRI" },
    { name = "IO_MUX" },
    # { name = "LEDC" }, # TODO: define later
    { name = "LP_ANA" },
    { name = "LP_AON" },
    { name = "LP_APM" },
    { name = "LP_CLKRST" },
    { name = "LPWR", pac = "LP_CLKRST" },
    # { name = "LP_GPIO" }, # TODO: add PAC manually later
    # { name = "LP_I2C0" },
    { name = "LP_IO_MUX" },
    { name = "LP_PERI", pac = "LPPERI" },
    { name = "LP_TEE" },
    { name = "LP_TIMER" },
    { name = "LP_WDT" },
    { name = "MEM_MONITOR" },
    { name = "MODEM_LPCON" },
    { name = "MODEM_SYSCON" },
    # { name = "OTP_DEBUG" },
    { name = "PAU" },
    { name = "PCR" },
    { name = "PMU" },
    { name = "SHA", interrupts = { peri = "SHA" } },
    { name = "SLC" },
    # { name = "SLCHOST" }, TODO: add PAC manually later
    # { name = "SPI0" },
    # { name = "SPI1" },
    # { name = "SPI2", interrupts = { peri = "SPI2" } },
    { name = "SYSTEM", pac = "PCR" },
    { name = "SYSTIMER" },
    { name = "TEE" },
    { name = "TIMG0", clock_group = "TIMG" },
    { name = "TIMG1", clock_group = "TIMG" },
    # { name = "TRACE0", pac = "TRACE" },
    { name = "UART0", interrupts = { peri = "UART0" }, stable = true, clock_group = "UART" },
    { name = "UART1", interrupts = { peri = "UART1" }, stable = true, clock_group = "UART" },
    { name = "USB_DEVICE", interrupts = { peri = "USB_DEVICE" } },

    { name = "BT", virtual = true },
    { name = "FLASH", virtual = true },
    # { name = "GPIO_DEDICATED", virtual = true },
    { name = "LP_CORE", virtual = true },
    { name = "SW_INTERRUPT", virtual = true },
    { name = "WIFI", virtual = true },
]

clocks = { system_clocks = { clock_tree = [
    # High-speed clock sources
    { name = "XTAL_CLK",    type = "source", values = "40",     output = "VALUE * 1_000_000", always_on = true },
    { name = "RC_FAST_CLK", type = "source",                    output = "17_500_000" },
    { name = "PLL_CLK",     type = "derived", from = "XTAL_CLK", output = "480_000_000" },

    # Low-speed clocks
    { name = "XTAL32K_CLK",  type = "source", output = "32768"   },
    { name = "OSC_SLOW_CLK", type = "source", output = "32768"   },
    { name = "RC_SLOW_CLK",  type = "source", output = "130_000" },

    # PLL divider taps
    { name = "PLL_F20M",  type = "generic", output = "PLL_CLK / 24" },
    { name = "PLL_F40M",  type = "generic", output = "PLL_CLK / 12" },
    { name = "PLL_F48M",  type = "generic", output = "PLL_CLK / 10" },
    { name = "PLL_F60M",  type = "generic", output = "PLL_CLK / 8"  },
    { name = "PLL_F80M",  type = "generic", output = "PLL_CLK / 6"  },
    { name = "PLL_F120M", type = "generic", output = "PLL_CLK / 4"  },
    { name = "PLL_F160M", type = "generic", output = "PLL_CLK / 3"  },

    # HP SOC clock root (PCR_SOC_CLK_SEL: XTAL, RC_FAST, PLL_F160M)
    { name = "HP_ROOT_CLK", type = "mux", variants = [
        { name = "XTAL",      outputs = "XTAL_CLK" },
        { name = "RC_FAST",   outputs = "RC_FAST_CLK" },
        { name = "PLL_F160M", outputs = "PLL_F160M" },
    ] },

    { name = "CPU_CLK", type = "generic", params = { divisor = "0..256" }, output = "HP_ROOT_CLK / (divisor + 1)" },
    
    # AHB_CLK divider: divider = (AHB_DIV_NUM + 1), <= 40MHz
    { name = "AHB_CLK", type = "generic", params = { divisor = "0..256" }, output = "HP_ROOT_CLK / (divisor + 1)" },

    { name = "APB_CLK", type = "generic", params = { divisor = "0..256" }, output = "AHB_CLK / (divisor + 1)" },

    { name = "XTAL_D2_CLK", type = "generic", output = "XTAL_CLK / 2" },
    { name = "LP_FAST_CLK", type = "mux", variants = [
        { name = "RC_FAST", outputs = "RC_FAST_CLK" },
        { name = "XTAL_D2", outputs = "XTAL_D2_CLK" },
        { name = "XTAL",    outputs = "XTAL_CLK" },
    ] },
    { name = "LP_SLOW_CLK", type = "mux", variants = [
        { name = "RC_SLOW",  outputs = "RC_SLOW_CLK" },
        { name = "XTAL32K",  outputs = "XTAL32K_CLK" },
        { name = "OSC_SLOW", outputs = "OSC_SLOW_CLK" },
    ] },

    { name = "TIMG_CALIBRATION_CLOCK", type = "mux", variants = [
        { name = "OSC_SLOW_CLK",    outputs = "OSC_SLOW_CLK" },
        { name = "RC_SLOW_CLK",     outputs = "RC_SLOW_CLK" },
        { name = "RC_FAST_DIV_CLK", outputs = "RC_FAST_CLK" },
        { name = "XTAL32K_CLK",     outputs = "XTAL32K_CLK" },
    ] },
], template_groups = [
    { group = "UART", clocks = [
        { name = "FUNCTION_CLOCK", type = "generic", output = "sclk / (div_num + 1)", params = { sclk = [
            { name = "XTAL",     outputs = "XTAL_CLK", default = true },
            { name = "PLL_F80M", outputs = "PLL_F80M" }, # in IDF, PLL_F80M is used, but in fact we'll just increase power consumption with it.
            { name = "RC_FAST",  outputs = "RC_FAST_CLK" },
        ], div_num = "0 .. 0x100" } },
        { name = "BAUD_RATE_GENERATOR", type = "generic", output = "(FUNCTION_CLOCK * 16) / (integral * 16 + fractional)", params = { fractional = "0..16", integral = "0..0x1000" } },
    ] },
    { group = "TIMG", clocks = [
        { name = "FUNCTION_CLOCK", type = "mux", variants = [
            { name = "XTAL_CLK",    outputs = "XTAL_CLK", default = true },
            { name = "RC_FAST_CLK", outputs = "RC_FAST_CLK" },
            { name = "PLL_F80M",    outputs = "PLL_F80M" },
        ] },
        { name = "WDT_CLOCK", type = "mux", variants = [
            { name = "XTAL_CLK",    outputs = "XTAL_CLK", default = true },
            { name = "RC_FAST_CLK", outputs = "RC_FAST_CLK" },
            { name = "PLL_F80M",    outputs = "PLL_F80M" },
        ] },
    ] },

] }, peripheral_clocks = { templates = [
    { name = "default_clk_en_template", value = "{{control}}::regs().{{conf_register}}().modify(|_, w| w.{{clk_en_field}}().bit(enable));" },
    { name = "clk_en_template", value = "{{default_clk_en_template}}" },
    { name = "rst_template", value = "{{control}}::regs().{{conf_register}}().modify(|_, w| w.{{rst_field}}().bit(reset));" },
    { name = "control", value = "crate::peripherals::SYSTEM" },
    { name = "conf_register", value = "{{peripheral}}_conf" },
    { name = "clk_en_field", value = "{{peripheral}}_clk_en" },
    { name = "rst_field", value = "{{peripheral}}_rst_en" },
], peripheral_clocks = [
    { name = "Uart0", template_params = { conf_register = "uart(0).conf", clk_en_field = "clk_en", rst_field = "rst_en" }, keep_enabled = true},
    { name = "Uart1", template_params = { conf_register = "uart(1).conf", clk_en_field = "clk_en", rst_field = "rst_en" } },
    { name = "Timg0", template_params = { conf_register = "timergroup(0).conf", clk_en_field = "clk_en", rst_field = "rst_en" }, keep_enabled = true },
    { name = "Timg1", template_params = { conf_register = "timergroup(1).conf", clk_en_field = "clk_en", rst_field = "rst_en" } },

    { name = "Systimer", template_params = { peripheral = "systimer" }, keep_enabled = true },
] } }


[device.interrupts]
support_status = "partial"
status_registers = 3
software_interrupt_count = 4
software_interrupt_delay = 24 # CPU speed dependent
controller = { Riscv = { flavour = "clic", interrupts = 32, priority_levels = 8 } }

[device.timergroup]
support_status = "partial"
instances = [{ name = "timg0" }, { name = "timg1" }]
timg_has_divcnt_rst = true

[device.systimer]
