[package]
name    = "canfd"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
esp-backtrace = { path = "../../../esp-backtrace", features = [
    "panic-handler",
    "println",
] }
esp-bootloader-esp-idf = { path = "../../../esp-bootloader-esp-idf" }
esp-hal = { path = "../../../esp-hal", features = ["log-04", "unstable"] }
esp-println = { path = "../../../esp-println", features = ["log-04"] }

[features]
esp32c5 = [
    "esp-backtrace/esp32c5",
    "esp-bootloader-esp-idf/esp32c5",
    "esp-hal/esp32c5",
]

[profile.release]
debug            = true
debug-assertions = true
lto              = "fat"
codegen-units    = 1
