[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[env]
ESP_LOG = "info"
SSID = "SSID"
PASSWORD = "PASSWORD"
TARGET_IP = "255.255.255.255"

[unstable]
build-std = ["alloc", "core"]
