INCLUDE "rom/esp32c5.rom.api.ld"
INCLUDE "rom/esp32c5.rom.coexist.ld"
INCLUDE "rom/esp32c5.rom.eco3.ld"
INCLUDE "rom/esp32c5.rom.heap.ld"
INCLUDE "rom/esp32c5.rom.ld"
INCLUDE "rom/esp32c5.rom.libgcc.ld"
INCLUDE "rom/esp32c5.rom.net80211.ld"
INCLUDE "rom/esp32c5.rom.phy.ld"
INCLUDE "rom/esp32c5.rom.pp.ld"
INCLUDE "rom/esp32c5.rom.rvfp.ld"
INCLUDE "rom/esp32c5.rom.spiflash.ld"
INCLUDE "rom/esp32c5.rom.systimer.ld"
INCLUDE "rom/esp32c5.rom.version.ld"

INCLUDE "rom/additional.ld"
