crate: esp-rtos

options:
  - name: tick_rate_hz
    description: "Tick rate of the task scheduler in Hertz"
    default:
      - value: 100
    constraints:
      - type:
          validator: positive_integer

  - name: light_sleep_min_us
    description: "Minimum predicted sleep duration, in microseconds, required for the auto light-sleep idle hook to enter light sleep instead of WFI."
    default:
      - value: 1000
    constraints:
      - type:
          validator: positive_integer

  - name: sw-task-overflow-detection
    description: "Enable software-based stack overflow detection. The stack guard value and offset is based on esp-hal configuration."
    default:
      - value: false

  - name: stack-pointer-range-check
    description: "Enable range-check based stack overflow detection."
    default:
      - value: true

  - name: hw-task-overflow-detection
    description: "Enable hardware-based stack overflow detection. The stack watermark is based on the esp-hal stack-guard-offset configuration."
    default:
      - value: true
