support_status = "not_supported"
version = 2
has_input_sync = true
# PIN_FUNC_GPIO = 1 (from io_mux_reg.h)
gpio_function = 1
# From gpio_reg.h: 0x80 = constantly high, 0xC0 = constantly low
constant_0_input = 0xc0
constant_1_input = 0x80
# GPIO29 and GPIO41 are not bonded.
pins = [
    { pin =  0,                                                                 lp = { 0 = "LP_GPIO0" }, analog = { 0 = "XTAL_32K_N" } },
    { pin =  1,                                                                 lp = { 0 = "LP_GPIO1" }, analog = { 0 = "XTAL_32K_P" } },
    { pin =  2, functions = {                                   3 = "LCD_DATA19" }, lp = { 0 = "LP_GPIO2" } },
    { pin =  3, functions = {                                   3 = "LCD_DATA20" }, lp = { 0 = "LP_GPIO3" } },
    { pin =  4, functions = {                                   3 = "LCD_DATA21" }, lp = { 0 = "LP_GPIO4" } },
    { pin =  5, functions = {                                   3 = "LCD_DATA22" }, lp = { 0 = "LP_GPIO5" } },
    { pin =  6,                                                                 lp = { 0 = "LP_GPIO6" } },
    { pin =  7, functions = {                                   3 = "LCD_DATA23" }, lp = { 0 = "LP_GPIO7" } },
    { pin =  8, functions = { 2 = "GMAC_PHY_TXD0",               3 = "LCD_DATA0" } },
    { pin =  9, functions = { 0 = "FSPIHD",   2 = "GMAC_PHY_TXD1", 3 = "LCD_DATA1",  4 = "DBG_PSRAM_CK" } },
    { pin = 10, functions = { 0 = "FSPICS0",  2 = "GMAC_PHY_TXD2", 3 = "LCD_DATA2",  4 = "DBG_PSRAM_CS" } },
    { pin = 11, functions = { 0 = "FSPID",    2 = "GMAC_PHY_TXD3", 3 = "LCD_DATA3",  4 = "DBG_PSRAM_D" } },
    { pin = 12, functions = { 0 = "FSPICLK",  2 = "GMAC_PHY_TXEN", 3 = "LCD_DATA4",  4 = "DBG_PSRAM_Q" } },
    { pin = 13, functions = { 0 = "FSPIQ",    2 = "GMAC_RMII_CLK", 3 = "LCD_DATA5",  4 = "DBG_PSRAM_WP" } },
    { pin = 14, functions = { 0 = "FSPIWP",   2 = "GMAC_RX_CLK",   3 = "LCD_DATA6",  4 = "DBG_PSRAM_HOLD" } },
    { pin = 15, functions = { 0 = "FSPIIO4",  2 = "GMAC_PHY_RXDV", 3 = "LCD_DATA7",  4 = "DBG_PSRAM_DQ4" } },
    { pin = 16, functions = { 0 = "FSPIIO5",  2 = "GMAC_PHY_RXD3", 3 = "LCD_DATA8",  4 = "DBG_PSRAM_DQ5" } },
    { pin = 17, functions = { 0 = "FSPIIO6",  2 = "GMAC_PHY_RXD2", 3 = "LCD_DATA9",  4 = "DBG_PSRAM_DQ6" } },
    { pin = 18, functions = { 0 = "FSPIIO7",  2 = "GMAC_PHY_RXD1", 3 = "LCD_DATA10", 4 = "DBG_PSRAM_DQ7" } },
    { pin = 19, functions = { 0 = "FSPIDQS",  2 = "GMAC_PHY_RXD0", 3 = "LCD_DATA11", 4 = "DBG_PSRAM_DQS_0" } },
    { pin = 20, functions = { 0 = "SDIO_DATA0", 2 = "FSPICLK", 4 = "DBG_FLASH_CK" } },
    { pin = 21, functions = { 0 = "SDIO_DATA1", 2 = "FSPID",   4 = "DBG_FLASH_D" } },
    { pin = 22, functions = { 0 = "SDIO_DATA2", 2 = "FSPIQ",   4 = "DBG_FLASH_CS" } },
    { pin = 23, functions = { 0 = "SDIO_DATA3", 2 = "FSPICS0", 4 = "DBG_FLASH_Q" } },
    { pin = 24, functions = { 0 = "SDIO_CLK",   2 = "FSPIHD",  4 = "DBG_FLASH_WP" } },
    { pin = 25, functions = { 0 = "SDIO_CMD",   2 = "FSPIWP",  4 = "DBG_FLASH_HOLD" } },
    { pin = 26, functions = { 0 = "SPICS0" }, limitations = ["spi_flash"] },
    { pin = 27, functions = { 0 = "SPIQ" },   limitations = ["spi_flash", "strapping"] },
    { pin = 28, functions = { 0 = "SPIWP" },  limitations = ["spi_flash", "strapping"] },
    { pin = 30, functions = { 0 = "SPIHD" },  limitations = ["spi_flash"] },
    { pin = 31, functions = { 0 = "SPICLK" }, limitations = ["spi_flash"] },
    { pin = 32, functions = { 0 = "SPID" },   limitations = ["spi_flash"] },
    { pin = 33, functions = { 3 = "LCD_DATA12" }, analog = { 0 = "USJ_DM" } },
    { pin = 34, functions = { 3 = "LCD_DATA13" }, analog = { 0 = "USJ_DP" } },
    { pin = 35, functions = { 2 = "REF_GMAC_CLK",   3 = "LCD_DATA14", 4 = "SD2_CDATA0" } },
    { pin = 36, functions = { 2 = "GMAC_PHY_RXDV",  3 = "LCD_DATA15", 4 = "SD2_CDATA1" }, limitations = ["strapping"] },
    { pin = 37, functions = { 2 = "GMAC_PHY_TXEN",  3 = "LCD_DATA16", 4 = "SD2_CDATA2" }, limitations = ["strapping"] },
    { pin = 38, functions = { 2 = "GMAC_PHY_RXD3",  3 = "LCD_DATA17", 4 = "SD2_CDATA3" }, limitations = ["strapping"] },
    { pin = 39, functions = { 2 = "GMAC_PHY_RXD2",  3 = "LCD_DATA18", 4 = "SD2_CCLK" },  limitations = ["strapping"] },
    { pin = 40, functions = { 2 = "GMAC_PHY_RXD1",  3 = "LCD_PCLK",   4 = "SD2_CCMD" },  limitations = ["strapping"] },
    { pin = 42, functions = { 2 = "GMAC_RX_CLK" },                                      analog = { 1 = "ADC1_CH0" } },
    { pin = 43, functions = { 2 = "GMAC_RMII_CLK", 3 = "LCD_H_ENABLE" },                 analog = { 1 = "ADC1_CH1" } },
    { pin = 44, functions = { 2 = "GMAC_PHY_TXD0", 3 = "LCD_H_SYNC" },                   analog = { 1 = "ADC1_CH2" } },
    { pin = 45, functions = { 2 = "GMAC_PHY_TXD1", 3 = "LCD_V_SYNC" },                   analog = { 1 = "ADC1_CH3" } },
    { pin = 46, functions = { 2 = "GMAC_PHY_TXD2", 3 = "CAM_DATA0" },                    analog = { 1 = "ADC1_CH4" } },
    { pin = 47, functions = { 2 = "GMAC_PHY_TXD3", 3 = "CAM_DATA1" },                    analog = { 1 = "ADC1_CH5" } },
    { pin = 48, functions = {                       3 = "CAM_DATA2" },                    analog = { 1 = "ADC1_CH6" } },
    { pin = 49, functions = {                       3 = "CAM_DATA3" },                    analog = { 1 = "ADC1_CH7" } },
    { pin = 50, functions = {                       3 = "CAM_DATA4" },                    analog = { 1 = "ADC2_CH0" } },
    { pin = 51, functions = {                       3 = "CAM_DATA5" },                    analog = { 1 = "ADC2_CH1" } },
    { pin = 52, functions = { 2 = "FSPICS0",        3 = "CAM_DATA6" },                    analog = { 1 = "ADC2_CH2" } },
    { pin = 53, functions = { 2 = "FSPICLK",        3 = "CAM_DATA7" },                    analog = { 1 = "ADC2_CH3" } },
    { pin = 54, functions = { 0 = "MTDO", 2 = "FSPID",  3 = "CAM_PCLK" },                 analog = { 1 = "ADC2_CH4" }, limitations = ["jtag"] },
    { pin = 55, functions = { 0 = "MTCK", 2 = "FSPIQ",  3 = "CAM_XCLK" },                 analog = { 1 = "ADC2_CH5" }, limitations = ["jtag"] },
    { pin = 56, functions = { 0 = "MTDI", 2 = "FSPIHD", 3 = "CAM_V_SYNC" },               analog = { 1 = "ADC2_CH6" }, limitations = ["jtag"] },
    { pin = 57, functions = { 0 = "MTMS", 2 = "FSPIWP", 3 = "CAM_H_SYNC" },               analog = { 1 = "ADC2_CH7" }, limitations = ["jtag"] },
    { pin = 58, functions = { 0 = "U0TXD" } },
    { pin = 59, functions = { 0 = "U0RXD" } },
    { pin = 60, limitations = ["strapping"] },
    { pin = 61, limitations = ["strapping"] },
]
input_signals = [
    # UART
    { name = "U0RXD",               id = 10 },
    { name = "U0CTS",               id = 11 },
    { name = "U0DSR",               id = 12 },
    { name = "U1RXD",               id = 13 },
    { name = "U1CTS",               id = 14 },
    { name = "U1DSR",               id = 15 },
    { name = "U2RXD",               id = 16 },
    { name = "U2CTS",               id = 17 },
    { name = "U2DSR",               id = 18 },
    { name = "U3RXD",               id = 137 },
    { name = "U3CTS",               id = 138 },
    { name = "U3DSR",               id = 139 },
    # I2S0
    { name = "I2SO_BCK",            id = 25 },
    { name = "I2S_MCLK",            id = 26 },
    { name = "I2SO_WS",             id = 27 },
    { name = "I2SI_SD",             id = 28 },
    { name = "I2SI_BCK",            id = 29 },
    { name = "I2SI_WS",             id = 30 },
    # SPI2 (FSPI)
    { name = "FSPICLK",             id = 53 },
    { name = "FSPIQ",               id = 54 },
    { name = "FSPID",               id = 55 },
    { name = "FSPIHD",              id = 56 },
    { name = "FSPIWP",              id = 57 },
    { name = "FSPICS0",             id = 62 },
    # I2C
    { name = "I2CEXT0_SCL",         id = 68 },
    { name = "I2CEXT0_SDA",         id = 69 },
    { name = "I2CEXT1_SCL",         id = 70 },
    { name = "I2CEXT1_SDA",         id = 71 },
    # USB JTAG
    { name = "USB_JTAG_TDO_BRIDGE", id = 140 },
    # CPU GPIO
    { name = "CPU_GPIO_0",          id = 214 },
    { name = "CPU_GPIO_1",          id = 215 },
    { name = "CPU_GPIO_2",          id = 216 },
    { name = "CPU_GPIO_3",          id = 217 },
    { name = "CPU_GPIO_4",          id = 218 },
    { name = "CPU_GPIO_5",          id = 219 },
    { name = "CPU_GPIO_6",          id = 220 },
    { name = "CPU_GPIO_7",          id = 221 },
    # Spare functions
    { name = "SIG_IN_FUNC251",      id = 251 },
    { name = "SIG_IN_FUNC252",      id = 252 },
    { name = "SIG_IN_FUNC253",      id = 253 },
    { name = "SIG_IN_FUNC254",      id = 254 },
    { name = "SIG_IN_FUNC255",      id = 255 },

    # IOMUX-only signals
    { name = "MTDO" },
    { name = "MTCK" },
    { name = "MTDI" },
    { name = "MTMS" },
    { name = "SDIO_DATA0" },
    { name = "SDIO_DATA1" },
    { name = "SDIO_DATA2" },
    { name = "SDIO_DATA3" },
    { name = "SDIO_CLK" },
    { name = "SDIO_CMD" },
    { name = "FSPIIO4" },
    { name = "FSPIIO5" },
    { name = "FSPIIO6" },
    { name = "FSPIIO7" },
    { name = "FSPIDQS" },
    { name = "SPICS0" },
    { name = "SPIQ" },
    { name = "SPIWP" },
    { name = "SPIHD" },
    { name = "SPICLK" },
    { name = "SPID" },
    { name = "GMAC_PHY_TXD0" },
    { name = "GMAC_PHY_TXD1" },
    { name = "GMAC_PHY_TXD2" },
    { name = "GMAC_PHY_TXD3" },
    { name = "GMAC_PHY_TXEN" },
    { name = "GMAC_RMII_CLK" },
    { name = "GMAC_RX_CLK" },
    { name = "GMAC_PHY_RXDV" },
    { name = "GMAC_PHY_RXD0" },
    { name = "GMAC_PHY_RXD1" },
    { name = "GMAC_PHY_RXD2" },
    { name = "GMAC_PHY_RXD3" },
    { name = "REF_GMAC_CLK" },
    { name = "LCD_DATA0" },
    { name = "LCD_DATA1" },
    { name = "LCD_DATA2" },
    { name = "LCD_DATA3" },
    { name = "LCD_DATA4" },
    { name = "LCD_DATA5" },
    { name = "LCD_DATA6" },
    { name = "LCD_DATA7" },
    { name = "LCD_DATA8" },
    { name = "LCD_DATA9" },
    { name = "LCD_DATA10" },
    { name = "LCD_DATA11" },
    { name = "LCD_DATA12" },
    { name = "LCD_DATA13" },
    { name = "LCD_DATA14" },
    { name = "LCD_DATA15" },
    { name = "LCD_DATA16" },
    { name = "LCD_DATA17" },
    { name = "LCD_DATA18" },
    { name = "LCD_DATA19" },
    { name = "LCD_DATA20" },
    { name = "LCD_DATA21" },
    { name = "LCD_DATA22" },
    { name = "LCD_DATA23" },
    { name = "LCD_PCLK" },
    { name = "LCD_H_ENABLE" },
    { name = "LCD_H_SYNC" },
    { name = "LCD_V_SYNC" },
    { name = "CAM_DATA0" },
    { name = "CAM_DATA1" },
    { name = "CAM_DATA2" },
    { name = "CAM_DATA3" },
    { name = "CAM_DATA4" },
    { name = "CAM_DATA5" },
    { name = "CAM_DATA6" },
    { name = "CAM_DATA7" },
    { name = "CAM_PCLK" },
    { name = "CAM_XCLK" },
    { name = "CAM_V_SYNC" },
    { name = "CAM_H_SYNC" },
    { name = "SD2_CDATA0" },
    { name = "SD2_CDATA1" },
    { name = "SD2_CDATA2" },
    { name = "SD2_CDATA3" },
    { name = "SD2_CCLK" },
    { name = "SD2_CCMD" },
    { name = "DBG_PSRAM_CK" },
    { name = "DBG_PSRAM_CS" },
    { name = "DBG_PSRAM_D" },
    { name = "DBG_PSRAM_Q" },
    { name = "DBG_PSRAM_WP" },
    { name = "DBG_PSRAM_HOLD" },
    { name = "DBG_PSRAM_DQ4" },
    { name = "DBG_PSRAM_DQ5" },
    { name = "DBG_PSRAM_DQ6" },
    { name = "DBG_PSRAM_DQ7" },
    { name = "DBG_PSRAM_DQS_0" },
    { name = "DBG_FLASH_CK" },
    { name = "DBG_FLASH_D" },
    { name = "DBG_FLASH_CS" },
    { name = "DBG_FLASH_Q" },
    { name = "DBG_FLASH_WP" },
    { name = "DBG_FLASH_HOLD" },
]
output_signals = [
    # UART
    { name = "U0TXD",               id = 10 },
    { name = "U0RTS",               id = 11 },
    { name = "U0DTR",               id = 12 },
    { name = "U1TXD",               id = 13 },
    { name = "U1RTS",               id = 14 },
    { name = "U1DTR",               id = 15 },
    { name = "U2TXD",               id = 16 },
    { name = "U2RTS",               id = 17 },
    { name = "U2DTR",               id = 18 },
    { name = "U3TXD",               id = 137 },
    { name = "U3RTS",               id = 138 },
    { name = "U3DTR",               id = 116 },
    # I2S0
    { name = "I2SO_BCK",            id = 25 },
    { name = "I2S_MCLK",            id = 26 },
    { name = "I2SO_WS",             id = 27 },
    { name = "I2SO_SD",             id = 28 },
    { name = "I2SI_BCK",            id = 29 },
    { name = "I2SI_WS",             id = 30 },
    # SPI2
    { name = "FSPICLK",             id = 53 },
    { name = "FSPIQ",               id = 54 },
    { name = "FSPID",               id = 55 },
    { name = "FSPIHD",              id = 56 },
    { name = "FSPIWP",              id = 57 },
    { name = "FSPICS0",             id = 62 },
    { name = "FSPICS1",             id = 63 },
    { name = "FSPICS2",             id = 64 },
    { name = "FSPICS3",             id = 65 },
    { name = "FSPICS4",             id = 66 },
    { name = "FSPICS5",             id = 67 },
    # I2C
    { name = "I2CEXT0_SCL",         id = 68 },
    { name = "I2CEXT0_SDA",         id = 69 },
    { name = "I2CEXT1_SCL",         id = 70 },
    { name = "I2CEXT1_SDA",         id = 71 },
    # CPU GPIO
    { name = "CPU_GPIO_0",          id = 214 },
    { name = "CPU_GPIO_1",          id = 215 },
    { name = "CPU_GPIO_2",          id = 216 },
    { name = "CPU_GPIO_3",          id = 217 },
    { name = "CPU_GPIO_4",          id = 218 },
    { name = "CPU_GPIO_5",          id = 219 },
    { name = "CPU_GPIO_6",          id = 220 },
    { name = "CPU_GPIO_7",          id = 221 },
    # GPIO passthrough
    { name = "GPIO",                id = 256 },

    # IOMUX-only signals
    { name = "MTDO" },
    { name = "MTCK" },
    { name = "MTDI" },
    { name = "MTMS" },
    { name = "SDIO_DATA0" },
    { name = "SDIO_DATA1" },
    { name = "SDIO_DATA2" },
    { name = "SDIO_DATA3" },
    { name = "SDIO_CLK" },
    { name = "SDIO_CMD" },
    { name = "FSPIIO4" },
    { name = "FSPIIO5" },
    { name = "FSPIIO6" },
    { name = "FSPIIO7" },
    { name = "FSPIDQS" },
    { name = "SPICS0" },
    { name = "SPIQ" },
    { name = "SPIWP" },
    { name = "SPIHD" },
    { name = "SPICLK" },
    { name = "SPID" },
    { name = "GMAC_PHY_TXD0" },
    { name = "GMAC_PHY_TXD1" },
    { name = "GMAC_PHY_TXD2" },
    { name = "GMAC_PHY_TXD3" },
    { name = "GMAC_PHY_TXEN" },
    { name = "GMAC_RMII_CLK" },
    { name = "GMAC_RX_CLK" },
    { name = "GMAC_PHY_RXDV" },
    { name = "GMAC_PHY_RXD0" },
    { name = "GMAC_PHY_RXD1" },
    { name = "GMAC_PHY_RXD2" },
    { name = "GMAC_PHY_RXD3" },
    { name = "REF_GMAC_CLK" },
    { name = "LCD_DATA0" },
    { name = "LCD_DATA1" },
    { name = "LCD_DATA2" },
    { name = "LCD_DATA3" },
    { name = "LCD_DATA4" },
    { name = "LCD_DATA5" },
    { name = "LCD_DATA6" },
    { name = "LCD_DATA7" },
    { name = "LCD_DATA8" },
    { name = "LCD_DATA9" },
    { name = "LCD_DATA10" },
    { name = "LCD_DATA11" },
    { name = "LCD_DATA12" },
    { name = "LCD_DATA13" },
    { name = "LCD_DATA14" },
    { name = "LCD_DATA15" },
    { name = "LCD_DATA16" },
    { name = "LCD_DATA17" },
    { name = "LCD_DATA18" },
    { name = "LCD_DATA19" },
    { name = "LCD_DATA20" },
    { name = "LCD_DATA21" },
    { name = "LCD_DATA22" },
    { name = "LCD_DATA23" },
    { name = "LCD_PCLK" },
    { name = "LCD_H_ENABLE" },
    { name = "LCD_H_SYNC" },
    { name = "LCD_V_SYNC" },
    { name = "CAM_DATA0" },
    { name = "CAM_DATA1" },
    { name = "CAM_DATA2" },
    { name = "CAM_DATA3" },
    { name = "CAM_DATA4" },
    { name = "CAM_DATA5" },
    { name = "CAM_DATA6" },
    { name = "CAM_DATA7" },
    { name = "CAM_PCLK" },
    { name = "CAM_XCLK" },
    { name = "CAM_V_SYNC" },
    { name = "CAM_H_SYNC" },
    { name = "SD2_CDATA0" },
    { name = "SD2_CDATA1" },
    { name = "SD2_CDATA2" },
    { name = "SD2_CDATA3" },
    { name = "SD2_CCLK" },
    { name = "SD2_CCMD" },
    { name = "DBG_PSRAM_CK" },
    { name = "DBG_PSRAM_CS" },
    { name = "DBG_PSRAM_D" },
    { name = "DBG_PSRAM_Q" },
    { name = "DBG_PSRAM_WP" },
    { name = "DBG_PSRAM_HOLD" },
    { name = "DBG_PSRAM_DQ4" },
    { name = "DBG_PSRAM_DQ5" },
    { name = "DBG_PSRAM_DQ6" },
    { name = "DBG_PSRAM_DQ7" },
    { name = "DBG_PSRAM_DQS_0" },
    { name = "DBG_FLASH_CK" },
    { name = "DBG_FLASH_D" },
    { name = "DBG_FLASH_CS" },
    { name = "DBG_FLASH_Q" },
    { name = "DBG_FLASH_WP" },
    { name = "DBG_FLASH_HOLD" },
]
