[package]
name    = "ble_1-0"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
embassy-executor = "0.9.0"
embassy-futures = "0.1"
embassy-sync = "0.7"
embassy-time = "0.5.0"
esp-alloc = { version = "0.9.0" }
esp-backtrace = { version = "0.18.0", features = [
    "panic-handler",
    "println",
] }
esp-bootloader-esp-idf = { version = "0.4.0" }
esp-hal = { version = "1.0.0", features = ["log-04", "unstable"] }
esp-println = { version = "0.16.0", features = ["log-04"] }
esp-rtos = { version = "0.2.0", features = ["esp-radio", "embassy", "log-04"] }
esp-radio = { version = "0.17.0", features = [
    "ble",
    "log-04",
    "unstable",
] }
log = "0.4.27"
trouble-host = { version = "0.5.0", features = [
    "default-packet-pool-mtu-255",
    "derive",
    "scan",
] }
static_cell = "2.1.1"

[profile.release]
debug            = true
debug-assertions = true
lto              = "fat"
codegen-units    = 1

[package.metadata.cargo-machete]
# static_cell is used indirectly in #[gatt_service] macro.
ignored = ["embassy-sync", "static_cell"]
