INCLUDE "rom/esp32c6.rom.api.ld"
INCLUDE "rom/esp32c6.rom.coexist.ld"
INCLUDE "rom/esp32c6.rom.heap.ld"
INCLUDE "rom/esp32c6.rom.ld"
INCLUDE "rom/esp32c6.rom.libgcc.ld"
INCLUDE "rom/esp32c6.rom.net80211.ld"
INCLUDE "rom/esp32c6.rom.phy.ld"
INCLUDE "rom/esp32c6.rom.pp.ld"
INCLUDE "rom/esp32c6.rom.rvfp.ld"
INCLUDE "rom/esp32c6.rom.spiflash.ld"
INCLUDE "rom/esp32c6.rom.version.ld"

INCLUDE "rom/additional.ld"
