[package]
name          = "esp-metadata"
version       = "0.10.1"
edition       = "2024"
rust-version  = "1.95.0"
description   = "Metadata for Espressif devices"
documentation = "https://docs.espressif.com/projects/rust/esp-metadata/latest/"
repository    = "https://github.com/esp-rs/esp-hal"
license       = "MIT OR Apache-2.0"
publish       = false

[package.metadata.espressif]
needs-build-std = false
forever-unstable = true
changelog-exempt = true
check-configs = [
    { features = [] },
]
clippy-configs = [] # don't waste time on this

[dependencies]
anyhow       = "1.0"
convert_case = "0.8"
env_logger   = { version = "0.11.5", default-features = false, features = ["auto-color"] }
prettyplease = "0.3"
toml         = { version = "1.1", features = ["preserve_order"] }
serde        = { version = "1.0", default-features = false, features = ["derive", "std"] }
sha2         = "0.10"
somni-parser = "0.3"
somni-expr   = "0.3"
syn          = { version = "3", default-features = false, features = ["full", "parsing"] }
proc-macro2  = "1"
quote        = "1"
indexmap     = { version = "2", features = ["serde"] }
log          = "0.4.22"
walkdir      = "2.5.0"

[profile.dev]
debug = 0 # unnecessary for general use
