# Check with a local registry.
#
# We want to check if we can compile examples/tests after bumping the deps by using a local registry.
# (i.e. if we will publish the right set of crates)

name: pre-release-checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'release-pr')) }}

    steps:
      - uses: actions/checkout@v6

      # Install the Rust toolchain for Xtensa devices:
      - uses: esp-rs/xtensa-toolchain@v1.6
        with:
          version: 1.95.0.0

      # Install the Rust stable toolchain for RISC-V devices:
      - uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf,riscv32imac-unknown-none-elf,riscv32imafc-unknown-none-elf
          toolchain: stable
          components: rust-src

      # Install the Rust nightly toolchain for RISC-V devices:
      - uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf,riscv32imac-unknown-none-elf,riscv32imafc-unknown-none-elf
          toolchain: nightly
          components: rust-src

      - name: init-local-registry
        run: |
          # this example relies on a Cargo.lock file and won't compile after `cargo update` - for now lets remove it
          # include it once that is resolved
          rm -rf examples/async/embassy_usb_ethernet

          cargo xrel-check init
          cargo xrel-check update
          cargo xrel-check replace-path-deps

      - name: try-build
        shell: bash
        run: |
          # lints and docs are checked a couple of times already by other workflows
          cargo xcheck ci esp32 --toolchain esp --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain esp --package=compile-tests all --chip=esp32

          cargo xcheck ci esp32s2 --toolchain esp --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain esp --package=compile-tests all --chip=esp32s2

          cargo xcheck ci esp32s3 --toolchain esp --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain esp --package=compile-tests all --chip=esp32s3

          cargo xcheck ci esp32c2 --toolchain stable --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain stable --package=compile-tests all --chip=esp32c2

          cargo xcheck ci esp32c3 --toolchain stable --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain stable --package=compile-tests all --chip=esp32c3

          cargo xcheck ci esp32c5 --toolchain stable --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain stable --package=compile-tests all --chip=esp32c5

          cargo xcheck ci esp32c6 --toolchain stable --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain stable --package=compile-tests all --chip=esp32c6

          cargo xcheck ci esp32c61 --toolchain stable --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain stable --package=compile-tests all --chip=esp32c61

          cargo xcheck ci esp32p4 --toolchain stable --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain stable --package=compile-tests all --chip=esp32p4

          cargo xcheck ci esp32h2 --toolchain stable --steps=lp-examples,examples,qa-test,tests
          cargo xtask build examples --toolchain stable --package=compile-tests all --chip=esp32h2
